### ISSUE TITLE
The volume slider from immersive mode remains displayed even after moving the pointer away from its active controller area

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2948] opened 2020-03-12 16:08 UTC
**[Affected Versions]:**
- Firefox Reality version 10-40720037 (dbb8ed3a)
- Firefox Reality version 8.1 (a0fcc8a3)
- Firefox Reality version 8 (ad776185)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on, the browser is installed and open.

**[Steps to reproduce]:**                                        
1. Go to a 360 video (e.g. https://youtu.be/hNAbQYU0wpg).
2. Play it and enter immersive mode.
3. Hover the volume button.
4. Point the pointer away from the volume slider and observe the behavior.

**[Expected results]:**
- The volume slider is dismissed.

**[Actual results]:**
- The volume slider remains displayed. 

**[Notes]:**
- The slider remains displayed across different videos.
- The issue is also reproducible for the other types of videos (180, normal, etc) when in immersive mode.
- Moving the pointer over the actionable area several times sometimes dismisses the slider.
- This issue is reproducible in production.
- Design [document](https://trello-attachments.s3.amazonaws.com/5a260c5d480978f87ffad6aa/5bd0ec2f89896a62d7978eca/ff3e0803782a1d13ccc3327d0bdcea33/UF-32_Volume_Controls_in_Transport_Controls_001.pdf) used as reference.
- Attached is a [recording](https://drive.google.com/file/d/1q8G19DHwP1M9byWGNZf3M9eh27O-gygR/view?usp=sharing) of this issue.

**Comment by keianhzo** [comment] 2020-04-09 16:52
asdsadasdasdsadasd
asdsadads

**Comment by daron-walters** [comment] 2020-04-16 19:52
[Link To Fix Video](https://drive.google.com/open?id=1uuoN0MKQSaLQl7GCkkwi3AEl91aisW2e[](url))

**Comment by daron-walters** [comment] 2020-04-22 01:46
here is a [video](https://drive.google.com/open?id=18eSqabJA-Agde0bfFpdFIVxgdK4SnJwz) of the fix

**Comment by Softvision-GeluHaiduc** [comment] 2020-04-23 12:12
I have verified this issue with the latest Firefox Reality version 10 RC1 (6db2f60a) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Unfortunately the volume slider still remains displayed even after moving the pointer away if previously it was slided to the max or min points on the slider. [Here](https://drive.google.com/file/d/1_OLVCMvhra-Ui7mnbUYTXQ1r4P6MoXXy/view?usp=sharing) is a video of the issue.

**Comment by bluemarvin** [comment] 2020-04-24 18:31
I think we only want to fix major and blocking issues for v10 at this point so moving this to v11.

**Comment by daron-walters** [comment] 2020-05-17 20:04
So from the video Gelu posted the issue is that the when dragging the volume slider to the max and min position sometimes the pointer would be dragged outside of the volume control area and the hover would never fire because the hover is outside of the controls area. Added a hover listener for the whole media control that if hover event is outside of control area we would fire a timer to hide c volume control.   [here](https://drive.google.com/open?id=1NGyl6gifFuN9qbyDUEfz76ATIvYxc5oB) is the video of the test from my local (tested on Oculus Quest)

**Comment by Softvision-GeluHaiduc** [comment] 2020-05-29 09:02
I have verified this issue with the latest Firefox Reality version 11-141492311 (a9b58ee6) installed on the Oculus Go, Pico Neo2 and Pico G2 4K headsets.
The issue seems to be fixed on the Oculus Go but unfortunately it is still reproducible on the Pico devices. [Here](https://drive.google.com/file/d/1AmP5zOs534EFsJhZu99QYB0XVuUfqtZL/view?usp=sharing) is a video of the issue, also I wasn't able to verify it on HTC.

**Comment by daron-walters** [comment] 2020-06-07 19:30
still researching and will discuss with team Monday just wanted to include my findings (in case i forget)

so the problem is in the Pico Platform Activity when the user clicks the slider and drags it outside of the area they keyup fires and this error gets hit in the onKeyUp of the VRActivity.  

here is log statement
2020-06-07 15:10:07.103 17690-17690/org.mozilla.vrbrowser.dev I/VRActivity: onKeyUp KeyCode = 127 dialogShow = -1

Here is a code snippet where it causes the problem 
   int var3 = PicovrSDK.GetDialogState(); 
  if (this.SeeThroughSettingExist && var3 >= 0) {
            ........
            }
        } else {
            Log.e("VRActivity", "onKeyUp Boundary Call SeeThrough Setting failed, is there this app?: " + this.SeeThroughSettingExist + ".   Is diaglog showed?: " + (var3 >= 0));
        }
this leads to the event getting cancelled because for some reason the Dialog State (var3) is -1

Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_MEDIA_PAUSE, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=19242479, downTime=19242479, deviceId=-1, source=0x101 }

**Comment by keianhzo** [comment] 2020-06-08 12:40
@daron-walters I think we should be able to handle the ACTION_CANCEL case here:

https://github.com/MozillaReality/FirefoxReality/blob/3f1172fbf7dc1eac5587d03f9bcf8711049a6937/app/src/common/shared/org/mozilla/vrbrowser/ui/views/VolumeControl.java#L51-L56

And hide the view in that case.

**Comment by daron-walters** [comment] 2020-06-08 17:07
reply @keianhzo thanks for that Manuel I had something similar on my local but I wasnt confident it would be the best solution

**Closed** 2020-06-15 11:55 UTC
Labels: [QA]:Minor issue, good first issue, in progress

**Comment by Softvision-GeluHaiduc** [comment] 2020-06-16 09:14
I have verified this issue with the latest Firefox Reality version 11-141672019 (418d959e) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the volume slider from immersive mode doesn't remain displayed after moving the pointer away from its active controller area.
