### ISSUE TITLE
[Oculus] A Transparent background is wrongly displayed for the menus, prompts and buttons

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3109] opened 2020-04-06 09:21 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140941948 (b539410).

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned.

**[Steps to reproduce]:**                                        
1. Open the Firefox Reality app.
2. Open the History library so that the background gets dimmed.
3. Observe the area of the navigation buttons.

**[Expected results]:**
- The UI is correctly displayed.

**[Actual results]:**
- A transparent background is visible.

**[Additional Notes]:**
- This issue is also visible for the prompts and menus available.
- The issue is highly visible when the background is dimmed.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1ZEDE08G6N7E2B0QPjfcQM3eNkvoiV3gq).

**Comment by bluemarvin** [comment] 2020-04-06 15:32
This is a driver bug in Oculus Runtime 15. There is nothing we can do about it until oculus fixes the driver.

**Comment by bluemarvin** [comment] 2020-04-06 17:13
My quest must have received and update today as the issue is no longer happening on my device.

**Comment by emstanley** [comment] 2020-04-06 18:09
Please make sure you have the most recent update that includes the bug fix and retest.

**Comment by bluemarvin** [comment] 2020-04-06 23:15
Sorry, it was not fixed for me with a software update, but we have confirmation from oculus that it is their bug and will be fixed in v16.

**Comment by bluemarvin** [comment] 2020-04-06 23:40
Oculus has recommended a work around that appears to work.

**Closed** 2020-04-07 23:48 UTC
Labels: [QA]:Normal issue, blocked-oculus, platform:Oculus, regression

**Comment by Softvision-RemusDranca** [comment] 2020-04-08 11:49
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-140982354 (bce60f9) build. The transparent background around the buttons/prompts and menus is no longer displayed.

Tested on Oculus Quest (Android 7.1.1) and Oculus Go (Android 7.1.2) devices.
