### ISSUE TITLE
A-frame and html5 audio play not working 

### ISSUE THREAD

**Issue by aerchit** [MozillaReality/FirefoxReality#1284] opened 2019-05-31 11:06 UTC
## Hardware
Vive Focus

## Steps to Reproduce
1. use A-frame <a-audio> or
2. use html5 audio tag

## Current Behavior
does not play, but same page plays in Chrome and Firefox

## Expected Behavior
play background music as soon as entering a VR scene

## Possible Solution
NA

## Context
I was working on a web VR project using A-frame and Three.js
I need an auto-play narration for my scene   

## Error Logs and Stack Traces
NA
<details open>

```
```

</details>

**Comment by philip-lamb** [comment] 2019-06-05 21:50
Duplicate of #1231

**Closed by philip-lamb** 2019-06-05 21:50 UTC
Labels: duplicate
