### ISSUE TITLE
Scrolling back to the top of a long page is tedious.

### ISSUE THREAD

**Issue by blue5peed** [MozillaReality/FirefoxReality#880] opened 2018-12-02 08:33 UTC
## Hardware
Oculus Go

## Current Behavior
User must use the touch pad swiping up many times to reach the top (or bottom) this is can be tiresome for long pages and fatigues your thumb.
Edit: Just realized that the user can drag the page by clicking it with the trigger then flicking the controller. That scrolls it in the chosen direction which is a less tedious method but may still require multiple clicks and flicks of the controller depending on the length of the page.

## Possible Solution
1. User should be able to drag the scroll Bar to navigate swiftly to any point.
2. Once a user has moved some distance from the top of a page a button could appear (or it could be visible and clickable at anytime). When clicked the page will scroll automatically to the top. 

```
```

</details>

**Comment by bluemarvin** [comment] 2018-12-04 21:36
Duplicate of Issue #317

**Closed by bluemarvin** 2018-12-04 21:36 UTC
Labels: duplicate
