### ISSUE TITLE
Feature request: Firefox Sync

### ISSUE THREAD

**Issue by Tomires** [MozillaReality/FirefoxReality#549] opened 2018-09-19 08:25 UTC
## Hardware
Oculus Go

## Feature Request
As a user of both the desktop and mobile version of FF, I would also appreciate an implementation of the Sync feature (hope I got the name right, it's the one that allows the user to send tabs across devices), which could help alleviate the terrible typing experience on 3DOF headsets.

```
```

</details>

**Comment by philip-lamb** [comment] 2019-05-17 00:50
This work will be implemented as part of Firefox Accounts. Closing as duplicate of #717

**Closed by philip-lamb** 2019-05-17 00:50 UTC
Labels: P3, enhancement
