### ISSUE TITLE
The app crashes after quickly enabling/disabling PB mode a few times while having multiple windows opened 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1705] opened 2019-08-29 14:21 UTC
**[Affected Versions]:**
- Firefox Reality 1.4-32402232 (08.29.2019)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32402232 (08.29.2019) apk. installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Open 2 new windows by clicking the "+" button 2 times.
2. Click the "Private Browsing" button from the same tray.
3. Open 2 new windows while in Private browsing mode.
4. Quickly click the "Private Browsing" button for ~10 times.
5. Observe the behavior.

**[Expected results]:**
- Private Browsing mode is successfully enabled/disabled each time.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- On Oculus Quest device I have encountered an additional intermittent behavior, where the app freezes and the device needs to be restarted.
- I was not able to reproduce this issue on HTC Vive Focus Plus device.
- Attached are screen recordings of the issue for both devices and the crash report:
	- Oculus Go recording: [link](https://drive.google.com/open?id=1l3x1GUfjgSMKuTFxfdhOYny3L71w5PqW)
	- Oculus Quest recording: [link](https://drive.google.com/open?id=10KLLwnETHr9L2LzmMWutUdgwEqLTzHq9)
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/bp-d6046995-f6b7-4d99-8203-7dd0e0190829)

**Comment by bluemarvin** [comment] 2019-08-29 17:35
While I can't reproduce the crash, we seem to be leaking surfaces from the VR compositor. After a certain point they seem to get exhausted and all new layers are rendered as large black squares:
![Screen_Shot_1908295511](https://user-images.githubusercontent.com/3066/63962902-a834cf00-ca48-11e9-8a78-2f876379ecd9.png)

**Comment by bluemarvin** [comment] 2019-08-29 21:02
From my testing this is only an issue on the Quest now. https://github.com/MozillaReality/FirefoxReality/pull/1707 seems to have fixed it on the Go in combination with a system update.

**Comment by Softvision-RemusDranca** [comment] 2019-08-30 11:13
I've  retested this issue on Oculus Go device and it's no longer reproducible with the latest 1.4-32420004 (RC1) build.

**Comment by bluemarvin** [comment] 2019-08-30 17:58
Fixed on Quest by #1716

**Comment by Softvision-RemusDranca** [comment] 2019-09-03 12:56
It seems that the tables have turned, now the issue is not reproducible on Oculus Quest and again reproducible on Oculus GO with the 1.4-32450938 (RC2) build.
Here is the [link](https://crash-stats.mozilla.com/report/index/bp-c8a977d1-6e7d-4a29-9658-1214e0190902) for the crash report on Oculus GO.
Considering this I will reopen this issue.

**Comment by MortimerGoro** [comment] 2019-09-03 16:33
I can reproduce it on 64 bit builds for Oculus Go. It works ok on 32bit builds

**Comment by bluemarvin** [comment] 2019-09-03 17:00
Looks like https://github.com/MozillaReality/FirefoxReality/pull/1716 is related to the crash on Go.

**Closed** 2019-09-04 16:28 UTC
Labels: [QA]:Major issue

**Comment by Softvision-GeluHaiduc** [comment] 2019-09-06 12:06
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32481747 RC3 installed on the Oculus Go, Quest and HTC Vive Focus Plus headsets. 
Now, the app doesn't crash after quickly enabling/disabling PB mode a few times while having multiple windows opened.
