### ISSUE TITLE
The windows are frozen after resuming the app while in immersive mode on videos using WebVR

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3117] opened 2020-04-06 14:31 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140941948 (b539410).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Open the "Hello WebXR" card from homepage and play it in immersive mode.
2. Click the Pico button.
3. Reopen the app and interact with the windows.

**[Expected results]:**
- The windows are responsive.

**[Actual results]:**
- The windows are frozen and can't be navigated.

**[Additional Notes]:**
- This issue is also reproducible after exiting sleep mode.
- I was also able to reproduce this issue with the "https://krpano.com/examples/" website.
- New created windows are not affected by this issue.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1x_QIKsVu2YK0DmHtryB_4weeyFYAFDRy).

**Comment by bluemarvin** [comment] 2020-04-06 17:16
Is this intermittent? I am not able to reproduce it on the Neo2 or the Quest. I tried with both debug an a release build.

**Comment by Softvision-RemusDranca** [comment] 2020-04-07 15:01
I've retested this issue  with the latest Firefox Reality version 10-140941948 (633529f) build and I can reproduce this issue almost every time, even after reinstalling the app. I reproduced it 9 times from 10 attempts.
Here are two recordings on different websites and devices:
Oculus Quest: [link](https://drive.google.com/open?id=1YHs6An8sY4jeFerL1LMvVS_0lv6-SB_H).
Pico Neo2: [link](https://drive.google.com/open?id=1HgGLWHql69qcRfox_3b-0BEKXOzR-sE-).

**Comment by bluemarvin** [comment] 2020-04-07 15:23
@keianhzo or @MortimerGoro can either of you reproduce this?

**Comment by MortimerGoro** [comment] 2020-04-08 23:56
I have seen some instances of this lately. I have been trying WebXR a lot, it's not related to videos specifically

**Comment by MortimerGoro** [comment] 2020-04-09 15:32
Fixed in #3141

**Closed by MortimerGoro** 2020-04-09 15:32 UTC
Labels: [QA]:Major issue, regression

**Comment by Softvision-RemusDranca** [comment] 2020-04-14 10:31
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-141042250 (207f86b) build. The windows can be navigated after resume. I was not able to reproduce it in 10 attempts.

Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2), HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
