### ISSUE TITLE
Adjust how window appears to move closer/farther from user when using resizing handles in Focus Mode

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#215] opened 2018-07-19 22:04 UTC
Hardware: All
Steps to Reproduce: Making window smaller or larger with control handles appears to move window further or closer to user
Actual Behavior: Making window smaller or larger with control handles appears to move window further or closer to user
Expected Behavior: Window stays at same perceived distance from user while being made smaller or larger
Recommendation: ? needs exploration

From Youtube video review - link has timestamp: https://youtu.be/YfF0R2v0kEk?t=255

**Comment by avrignaud** [comment] 2018-07-19 22:09
Also related, reviewer commented that it would be nice to be able to position a "big screen further away" than as close as it seems to get. I think he may be referring to a movie theater like effect, where you want to be able to have a huge screen but at a greater distance so it fits within easy eye scanning distance.

**Comment by bluemarvin** [comment] 2018-07-20 19:55
This effect probably won't be as bad in the meadow. The problem is the human brain only uses stereo to judge distance for things much closer than the window. For object at the distance of the window, your brain uses other cues such as shadows or other objects of known sizes. Since the current space theme doesn't have any of that, when the window changes size, your brain helpfully decides, this object is moving closer and father away because it is getting bigger/smaller.

**Comment by thenadj** [comment] 2018-07-24 00:16
Here's the explanation of what's happening from a friend who recently saw FxR:
"It’s called Solid Angle.  Basically how much of your field of view is taken up by an object.  Defined I think as the Area of an object divided by the square of the distance to that object. 
But your objects don’t have area, so you would need to calculate in a different way.
We get a sense of how far something is by the solid angle and our knowledge of an object’s intrinsic size.  For example, a car on the highway."

**Comment by thenadj** [comment] 2018-07-24 00:17
That said, it still appears to move in distance upon resizing, even with the new environment.

**Comment by bluemarvin** [comment] 2018-07-24 00:22
A fake shadow underneath would help. but it would have to be resized so it couldn't be baked in.

**Comment by philip-lamb** [comment] 2019-03-04 12:17
The non-perceptual aspects of this item are adequately covered in #480. Closing as duplicate.

**Closed** 2019-03-04 12:18 UTC
Labels: P1, bug, duplicate
