### ISSUE TITLE
Improvement: allow using Bluetooth keyboard

### ISSUE THREAD

**Issue by assadollahi** [MozillaReality/FirefoxReality#1390] opened 2019-07-12 06:39 UTC
## Hardware
Oculus  Quest, bluetooth keyboard successfully paired.

## Steps to Reproduce
keyboard can be used in Oculus browser but not in Firefox Reality browser.

## Current Behavior
keystrokes are not received in browser applications

## Expected Behavior
keystrokes should be registered in browser applications 

```
```

**Comment by jvonitter** [comment] 2019-07-13 00:10
duplicate of #775

**Closed by jvonitter** 2019-07-13 00:10 UTC
