### ISSUE TITLE
Typed characters appear to the right of the cursor on Bluetooth keyboard.

### ISSUE THREAD

**Issue by ghost** [MozillaReality/FirefoxReality#2578] opened 2020-01-03 10:38 UTC
## Configuration

Firefox Reality version: 7(Release Version)
Firefox Reality build ID: unknown

Hardware: Oculus Quest 

## Steps to Reproduce

1.Position the cursor on the text input form.
2.Press two letter keys simultaneously on a Bluetooth keyboard.
3.Hit repeatedly.

## Current Behavior

One of the keys pressed simultaneously appears to the right of the cursor.
This bug occurs quite often during heavy processing.
As a result, the order of the characters is incorrect.

## Expected Behavior

Characters appear sequentially to the left of the cursor.

## Context

I want to type correctly on a Bluetooth keyboard.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by gaegaelab** [comment] 2020-02-13 16:03
![ezgif-6-a2c620d9067b (1)](https://user-images.githubusercontent.com/5130723/74452976-2258f300-4ec5-11ea-8536-8b12e7f406fa.gif)
In this video, I hit J and K repeatedly.
Due to a bug, sometimes K is added to the right of the cursor.
It's very inconvenient when coding, so it would be very helpful if you could fix it.

**Comment by bluemarvin** [comment] 2020-02-13 16:24
This is a known issue: https://github.com/MozillaReality/FirefoxReality/issues/2290

A fix should have landed in GeckoView today so hopefully will be fixed in FxR v9.

**Comment by gaegaelab** [comment] 2020-02-13 16:41
Thank you for your reply!
I am very happy to hear the information.

**Comment by J-Tech-Foundation** [comment] 2020-02-14 15:27
if you change your user agent to that of chrome or ipad, this bug will be resolved!

**Comment by bluemarvin** [comment] 2020-02-14 16:32
> if you change your user agent to that of chrome or ipad, this bug will be resolved!

This bug is not caused by the UA (you would need to recompile FxR to change the UA anyway). It is a known issue in Gecko https://bugzilla.mozilla.org/show_bug.cgi?id=1596920
The fix for this landed [yesterday](https://github.com/MozillaReality/FirefoxReality/pull/2783) in FxR so will be included in v9. This is a tricky issue so it is possible there may be more than one cause.

**Comment by J-Tech-Foundation** [comment] 2020-02-20 15:31
thanks for the update to that!

**Closed** 2024-07-22 11:45 UTC
Labels: ARCHIVED
