### ISSUE TITLE
The theater mode controls are briefly displayed when entering/exiting PB and when creating /dismissing a window

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3113] opened 2020-04-06 11:35 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140941948 (b5394107)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click the Private Browsing button in the menu tray.
2. Observe the awesomebar area.

**[Expected results]:**
- The PB awesomebar is displayed.

**[Actual results]:**
- The theater mode controls are briefly displayed.

**[Notes]:**
- The theater mode controls are also briefly displayed when exiting PB.
- The theater mode controls are also briefly displayed when creating or dismissing a new window.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Ld5rq2mmKEEs5ss_vCMVEcU-OtTRZbDi/view?usp=sharing).

**Comment by bluemarvin** [comment] 2020-04-06 17:59
This looks like a duplicate of #3112

**Closed** 2020-04-06 18:06 UTC
Labels: [QA]:Normal issue, duplicate, regression

**Comment by Softvision-GeluHaiduc** [comment] 2020-07-01 09:25
I have verified this issue with Firefox Reality version 11 RC2 (5fd1bfd0) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the theater mode controls are not briefly displayed when entering/exiting PB or when creating/dismissing a window.
