### ISSUE TITLE
Honeycomb buttons Void color on click/active state looks confusing

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#741] opened 2018-11-09 06:00 UTC
## Hardware
Oculus Go
5eeebbe

## Steps to Reproduce
1. Press the Settings icon in the Tray
2. Press and hold on one of the honeycomb buttons
3. Notice the active state turns black

## Current Behavior
Super minor:
![image](https://user-images.githubusercontent.com/203725/48245729-3009f980-e3a1-11e8-8fe9-1376984a4d4d.png)

## Expected Behavior
I wouldn't expect it to turn black; it looks like a bug. If it's working by design, my bad heh.

**Comment by keianhzo** [comment] 2018-11-15 23:39
Are you still seeing this in the latest voice-search-language https://github.com/MozillaReality/FirefoxReality/pull/728/commits/350af99d44b38a7c86cbbd35346c5f5bb67370a7 commit? I can't reproduce this anymore.

**Comment by cvan** [comment] 2018-11-20 10:08
> Are you still seeing this in the latest voice-search-language https://github.com/MozillaReality/FirefoxReality/pull/728/commits/350af99d44b38a7c86cbbd35346c5f5bb67370a7 commit? I can't reproduce this anymore.

yep, still can. if you press and hold with the Oculus Go primary trigger button, you should be able to reproduce it.

**Comment by philip-lamb** [comment] 2019-03-04 07:37
Is the preferred active state of the buttons specified in the design spec?

**Comment by cvan** [comment] 2019-03-05 09:49
This appears to be an, albeit nitpicky, engineering bug to fix for the focused (i.e., when the primary controller button is). #638 is a good issue to resolve, but this issue seems isolated enough, and the UI styles have been defined prior to that issue. This should be a simple fix.

**Comment by jvonitter** [comment] 2019-08-22 22:39
This is fixed as of 1.4

**Closed by jvonitter** 2019-08-22 22:39 UTC
Labels: P3, UX, enhancement
