### ISSUE TITLE
The mobile version of a webpage is displayed even though the desktop user agent is selected

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1473] opened 2019-07-30 09:09 UTC
**[Affected Versions]:**
- Firefox Reality 1.4-32101950

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- Go to "Settings"(gear icon), "Display" tile and for the "User-Agent Mode" setting select the "Desktop" option.

**[Steps to reproduce]:**
1. Visit the following webpage: "facebook.com".
2. Click the "Switch User Agent" button in the search bar. (The mobile version of the webpage is displayed)
3. Click the "Switch User Agent" button again. 
4. Observe the loaded webpage.

**[Expected results]:**
- The desktop version of the webpage is displayed.

**[Actual results]:**
- The mobile version of the webpage is displayed even though the desktop user agent is selected.

**[Notes]:**
- The issue is also reproducible with the twitter.com webpage.
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1pGqr74iTvhJWjNyU6XVFQvBHo0deQrRI/view?usp=sharing)

**Comment by jvonitter** [comment] 2019-07-31 22:20
Some sites dont give the desktop version even if we ask for it. We need to test with sites that report the UA they're getting, such as http://httpbin.org/#/Request_inspection/get_user_agent

**Comment by jvonitter** [comment] 2019-07-31 22:21
@Softvision-GeluHaiduc can you confirm that this isnt just a facebook problem?

**Comment by Softvision-GeluHaiduc** [comment] 2019-08-01 08:27
@jvonitter I tried different websites:
- on the following websites the issue is reproducible: “facebook.com”, “twitter.com” and “twitch.tv”.
- on the following websites the issue is not reproducible: “netflix.com”, “reddit.com”, “instagram.com“.

From what I saw the issue appears when the website has a **m.domain.com** for mobile user agent. (m.facebook.com, m.twitter.com, m.twitch.tv)

**Comment by keianhzo** [comment] 2019-08-01 11:30
@jvonitter @Softvision-GeluHaiduc The problem is that for pages that redirect to a mobeil domain if you change the UA to desktop when you are already in the mobile site we just reload the mobile site and you see the mobile site in desktop mode, same as if you just load https://m.twitter.com in your desktop browser. It's using the desktop UA but loading the mobile site.

Not sure if there is anything we can do about that @bluemarvin @MortimerGoro any ideas?

**Comment by Softvision-GeluHaiduc** [comment] 2019-08-01 12:47
@keianhzo I don't know if this information helps but on Firefox for android if you visit twitter.com and then check the option for “Request desktop site” the m.twitter.com website is loaded and if you uncheck the option the desktop version of the website is loaded twitter.com.

**Comment by bluemarvin** [comment] 2019-08-01 23:50
This is a bug in Fenix too. It might need GeckoView support. Here is the code in Fennec:  https://searchfox.org/mozilla-central/rev/b38e3beb658b80e1ed03e0fdf64d225bd4a40327/mobile/android/chrome/content/browser.js#4615

**Comment by bluemarvin** [comment] 2019-08-01 23:53
I'm working to determine if we can do something similar with current GV API or if we will need GV changes.

**Comment by bluemarvin** [comment] 2019-08-02 20:19
In order to fix this in FxR the following GeckoView issue need to be resolved:

https://bugzilla.mozilla.org/show_bug.cgi?id=1571083
https://bugzilla.mozilla.org/show_bug.cgi?id=1571088

**Comment by bluemarvin** [comment] 2019-08-09 23:13
From the PR:
This turning out to be more difficult that I first thought. The problem I am having is that in the twich.tv case specifically, it is a single page site. So we don't actually get `onLoadRequest()` for most link clicks on the site. so it is impossible to know when to not use the original URI that triggered the redirection. This also explains Fennec's similar behavior. What's needed is for `onLocationChange()` which does fire to include a parameter that indicates if the location change was caused by human interaction of clicking on a link or if it is just the page playing with the history.

**Comment by bluemarvin** [comment] 2019-08-15 22:51
This should be fixed with https://github.com/MozillaReality/FirefoxReality/pull/1542 so I think it might still make 1.4

**Closed** 2019-08-19 20:41 UTC
Labels: Bugzilla, P1, QA, [QA]:Normal issue, blocked, bug, needinfo

**Comment by Softvision-GeluHaiduc** [comment] 2019-08-20 06:08
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32312044 installed on the Oculus Go headset. 
Now, the correct version of a webpage is displayed depending on the user agent selected in thew awesomebar.
