### ISSUE TITLE
The “Thai” language in the keyboard language menu is not displayed in its native language

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3624] opened 2020-07-06 11:13 UTC
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f6453025)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Click the "Language" button from the keyboard.
3. Observe the “Thai” language.

**[Expected results]:**
- The “Thai” language is displayed in its native language.

**[Actual results]:**
- The “Thai” language is not displayed in its native language.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1pAV5Ep24ddIBRveLQJo_M3a4fZBMtXEp/view?usp=sharing).

**Comment by keianhzo** [comment] 2020-07-06 13:26
Duplicate of #3625

**Comment by emstanley** [comment] 2020-07-06 21:50
Closing this as a duplicate

**Closed** 2020-07-06 21:50 UTC
Labels: [QA]:Caught_by_exploratory, [QA]:Minor issue
