### ISSUE TITLE
[Pico][Intermittent] The app crashes when the Microphone permission prompt is displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3121] opened 2020-04-07 11:49 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140971439 (633529f).

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned.

**[Steps to reproduce]:**                                        
1. Open the app.
2. Click "Start Browsing" button from the prompt displayed.
3. Click the Microphone button from the Awesomebar.
4. Click the "Don't Allow" button from the Collect voice samples prompt.
5. Observe the behavior.

**[Expected results]:**
- The Microphone permission prompt is displayed.

**[Actual results]:**
- The Microphone permission prompt is briefly displayed and the app crashes.

**[Additional Notes]:**
- I was able to reproduce this issue mainly after a fresh install/update.
- Attached are a screen recording, crash report and the logcat of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=15vnJHLEUgBOnL6ej5pk60phH2aM4Uxcp).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/9db38936-236c-48fe-bf50-b635f0200407).
	- Logcat: [link](https://drive.google.com/open?id=1iE_26nlW8LkhvAAlEuW9TZMfRbat2PJo).

**Comment by keianhzo** [comment] 2020-04-07 15:09
@bluemarvin This seems to be related to the SDK crash that we have already shared with Pico.
https://crash-stats.mozilla.com/report/index/958226b4-206f-4ee9-b464-998b80200317

**Comment by bluemarvin** [comment] 2020-04-07 15:21
> @bluemarvin This seems to be related to the SDK crash that we have already shared with Pico.
> https://crash-stats.mozilla.com/report/index/958226b4-206f-4ee9-b464-998b80200317

Yep, this is the same crash in the Pico Runtime. There isn't much we can do without help from pico.

**Comment by bluemarvin** [comment] 2020-04-07 15:38
This is a dupe of  #2952

**Comment by keianhzo** [comment] 2020-04-07 16:44
Closing as it's already tracked.

**Closed by keianhzo** 2020-04-07 16:44 UTC
Labels: [QA]:Major issue, blocked-pico, duplicate, regression
