### ISSUE TITLE
Resize mode design dive

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#628] opened 2018-10-16 10:40 UTC
There are a few issues that have been reported around resize mode that we should dive into ASAP for 1.1. Some comments:
- https://github.com/MozillaReality/FirefoxReality/issues/371#issuecomment-418904860
- https://www.reddit.com/r/OculusGo/comments/8zccmj/firefox_reality_w_webvr_superalpha_release/e2hsj7k/

I believe that the issues center around a few things:
- What do we do with the various UI elements (tray, keyboard, URL bar, etc.) when we resize? If the browser gets very large, they can end up down at your feet and difficult to use.
- How do we handle zoom levels as part of or separate from the resize of the window.

There may be others, but comments appeared scattered in PRs and Slack threads, so I wanted to create an issue and suggest a deeper dive (meeting?) to detail the corner cases and talk through some of the tradeoffs.

**Comment by avrignaud** [comment] 2018-10-16 16:09
Making sure comment from 526 is captured: 
1.Window does not have handles on lower edges - due to occulusion challenges discussed in #463 (closed for 1.0).

**Comment by cvan** [comment] 2018-10-16 21:59
thanks for tracking these issues down and filing this!

related, posting for posterity's sake: https://github.com/MozillaReality/FirefoxReality/issues/371#issuecomment-418904860

**Comment by thenadj** [comment] 2018-10-25 16:21
Attached are some design explorations around resizing and repositioning the browser window. This is ready for review. 
[DE-30 Browser Positioning_003.pdf](https://github.com/MozillaReality/FirefoxReality/files/2515892/DE-30.Browser.Positioning_003.pdf)

**Comment by thenadj** [comment] 2018-10-31 17:29
Is this a dupe of: https://github.com/MozillaReality/FirefoxReality/issues/480#issuecomment-434731609 ?

**Comment by caseyyee** [comment] 2018-11-27 18:57
Closing for https://github.com/MozillaReality/FirefoxReality/issues/480

**Closed by caseyyee** 2018-11-27 18:57 UTC
Labels: Draft Design, Needs Design, P0, UX

**Comment by cvan** [comment] 2018-11-27 23:50
> Closing for #480

This issue seems specific to window resizing, while #480 is for moving the positions of the window, keyboard, etc.

IMO, we should break #480 into more granular sub-issues.

**Comment by caseyyee** [comment] 2018-11-28 00:16
Sure, i'm OK with leaving this open if you think it makes sense. I just figure that you can't solve one without fixing the other. Also, if you look at the design here (also posted), it addresses repositioning as well.
