### ISSUE TITLE
Creating a new window causes app to crash

### ISSUE THREAD

**Issue by jvonitter** [MozillaReality/FirefoxReality#1459] opened 2019-07-25 16:54 UTC
## Hardware
Oculus Quest
## Steps to Reproduce
Open and close new windows multiple times using the + button in the tray.

## Current Behavior
Viewport doesn't appear and app crashes.

## Expected Behavior
App doesnt crash.

## Context
I've been able to make this happen pretty reliably, but I can't tell what actually triggers it. Sometimes it's on the second new window and sometimes it's a lot later. I'm also not sure if switching to Private Browsing has something to do with it, but the first time it happened that's what I was doing, so I included it in the attached video.

```
```

</details>

**Comment by jvonitter** [comment] 2019-07-25 16:59
video:
https://send.firefox.com/download/c2356ead0eea8583/#DojmStP859OoTPPsEadJIg

**Comment by MortimerGoro** [comment] 2019-07-26 13:27
I have seen this behaviour too but can't reproduce it realiably either. Will take a deeper look because it can be a multiwindow blocker.

**Comment by keianhzo** [comment] 2019-08-01 08:15
I'm also having a hard time reproducing this. I've added a fix for hiding the left/right move buttons when in private move with a single window.

**Comment by MortimerGoro** [comment] 2019-08-01 11:05
I found a reliable way to reproduce this issue using a code change trick. Just add `mWidgetPlacement.width += 2;` in `WindowWidget` before calling mFirstDrawCallback.

We have some superfluous resizes which make the deadlock more likely (fixed in #1485).

I also added a fix to prevent this deadlock (#1486)

**Closed** 2019-08-02 09:03 UTC
Labels: bug, crash 🔥
