### ISSUE TITLE
Background texture corruption if we enter/exit WebVR before the model gets loaded

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#310] opened 2018-08-02 19:44 UTC
STR:

* Set https://webvr.info/samples/03-vr-presentation.html as the default web to make it easier to test this
* Enter & Exit WebVR before the background loads in the off-render thread
* The meadow texture is corrupter (a nice psychedelic color effect though XD)

**Comment by bluemarvin** [comment] 2018-08-02 21:43
I can reproduce this on GVR too. My theory is that the shared egl context only works as long as it's shared parent context is current. During immersive mode, a different egl context is current. I'm not sure how to fix this other than prevent going into immersive mode until the environment is loaded? e10s might also help since the webgl egl context would then be in a different process.

**Comment by bluemarvin** [comment] 2018-08-15 16:05
Now that load times are much faster, it is even harder to reproduce this. Once we have a startup slash screen it should no longer be possible for a user to encounter this issue. I recommend making this a P2 since the bug seems to be with the device ogl driver and finding a work around fix for it may be more work than it is worth right now.

**Comment by MortimerGoro** [comment] 2018-08-27 17:48
Changing this to P2 because we already have the splash and it's very difficult to enter WebVR before things are loaded. It can only happen on a really slow device such as Pixel 1. But we are going to switch to Cubemaps so it won't be a problem there either. 
cc @avrignaud @nancyhang

**Comment by larsbergstrom** [comment] 2018-09-08 21:01
Should we close this, since we have moved to cubemaps? Can revisit issues if we return to richer environments, though I would expect to only do that on much higher-end devices.

**Closed** 2018-11-02 20:54 UTC
Labels: P2, bug
