### ISSUE TITLE
Hubs audio only plays immediately after volume adjusted

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#3073] opened 2020-03-30 18:12 UTC
## Configuration

Firefox Reality version: 10-p1
Firefox Reality build ID: ac25341f

Hardware: Pico Neo 2

## Steps to Reproduce

1. Enter a Hubs room with a youtube video playing
2. Listen for the audio
3. Adjust volume

## Current Behavior

You can hear what's in the room, but only for 1 second immediately following volume adjustment

## Expected Behavior

Audio remains playing

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment] 2020-03-30 19:46
Is there a room with an example?

**Comment by bluemarvin** [comment] 2020-03-30 19:48
I can reproduce it here https://hubs.mozilla.com/SxkhBbN/audio-test

**Comment by bluemarvin** [comment] 2020-03-30 19:50
Looks like it is this: https://github.com/MozillaReality/FirefoxReality/issues/2620

**Comment by bluemarvin** [comment] 2020-03-30 20:13
https://bugzilla.mozilla.org/show_bug.cgi?id=1626081

I can reproduce the issue in GeckoViewExample.

**Comment by bluemarvin** [comment] 2020-04-13 17:19
There has been no action on this bug in Gecko.

**Comment by keianhzo** [comment] 2020-06-08 13:03
@bluemarvin I can't reproduce this with your example using the latest master. Any change that this has been fixed in GV without the patch?

**Closed** 2020-06-08 14:20 UTC
Labels: Bugzilla, blocked-media
