### ISSUE TITLE
Audio cuts out after mic permissions are confirmed in Hubs

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/FirefoxReality#2620] opened 2020-01-10 20:23 UTC
## Configuration

Firefox Reality version: 2020-01-08
Firefox Reality build ID: 4d0f9fb1

Quest

OS: oculus/vr_monterey/monterey:7.1.1/NGI77B/434260.5710.0:user/release-keys

1. Visit: https://hubs.mozilla.com/SxkhBbN/audio-test
2. Click somewhere on the screen other than the entry button, to get a user gesture. You should hear videos player.
3. Click through enter room flow, once you grant permissions, audio cuts out for remainder of session.

## Current Behavior
It seems that after granting microphone permissions, all audio is disabled in FxR. May be related to an OS upgrade since not reproducable on other devices.

## Expected Behavior
Audio should not cut out

```
```

</details>

**Comment by gfodor** [comment] 2020-01-10 20:24
Noticed that sometimes audio cuts out after mic permission granted, sometimes after entering immersive mode.

Also, I am not 100% positive, but I believe I may have experienced this in Oculus Browser as well. Still confirming however.

**Comment by bluemarvin** [comment] 2020-01-10 20:52
How often does it happen? I just tried the room about five times and audio worked as I would expect every time (I could hear the clip the whole time). I have seen audio issues on the quest that were fixed by a device restart. I also verified my device was running the current runtime (v12).

**Comment by gfodor** [comment] 2020-01-10 21:16
Thanks for checking. For me, it fails 100% of the time, even after a device restart. Hmm.

**Comment by bluemarvin** [comment] 2020-01-10 21:19
Here is the latest build: https://community-tc.services.mozilla.com/api/queue/v1/task/cHuWxX-7SOWBT6H9nKyWjA/runs/0/artifacts/public/FirefoxReality-8-40101959-oculusvr-arm64-staging-master-signed.apk
You will probably have to uninstall first: `adb uninstall org.mozilla.vrbrowser`

**Comment by gfodor** [comment] 2020-01-10 21:23
Well, when I try to install it adb fails (after uninstalling the old version) with no error message, and my USB connection just resets. Fun times.

**Comment by gfodor** [comment] 2020-01-10 21:25
ha ha. it was the USB cable.

**Comment by gfodor** [comment] 2020-01-10 21:30
Yup same problem. Two other things:

- In Oculus browser, the `play()` on `<audio>` seems to be broken. I escalated with those folks, may be related.

- I noticed after I grant mic permissions, the volume of the video either cuts out immediately, or briefly for 1 or 2 seconds plays at a much lower volume level, and then cuts out. I'm wondering if the volume is somehow being set on the stream (instead of something being broken.)

**Comment by gfodor** [comment] 2020-01-10 21:36
wrt the `play()` issue with Oculus Browser, this only breaks if mic permission is granted. still trying to get a repro on that issue as well tho.

**Comment by bluemarvin** [comment] 2020-01-10 22:33
Does it happen with the v7 release? https://github.com/MozillaReality/FirefoxReality/releases/download/release%2F7-rc6/FirefoxReality-7-33371749-oculusvr-arm64-release-signed.apk

The autoplay blocking code has changed in Gecko between v7 and v8 so that is one possible culprit. I'll try again to see if I can reproduce the issue locally.

**Comment by bluemarvin** [comment] 2020-01-10 22:55
I'm still not able to reproduce the issue. Is your system on the v12 Oculus runtime?

**Comment by gfodor** [comment] 2020-01-10 23:31
sorry, how do i check the oculus runtime? the OS version is OS: oculus/vr_monterey/monterey:7.1.1/NGI77B/434260.5710.0:user/release-keys

**Comment by bluemarvin** [comment] 2020-01-10 23:33
Go to the settings -> See All -> About

**Comment by bluemarvin** [comment] 2020-01-10 23:34
From the Oculus home shell.

**Comment by bluemarvin** [comment] 2020-01-10 23:36
![com oculus vrshell-20200110-153437](https://user-images.githubusercontent.com/3066/72193561-ef4fab00-33be-11ea-92c7-72343f4d87ba.jpg)

**Comment by gfodor** [comment] 2020-01-10 23:58
ah yep, 12.0.226.469 is the one i have too.

**Comment by bluemarvin** [comment] 2020-01-11 00:01
Have you tried with headphones? Maybe your speakers are going bad? I'll admit I'm now reaching since it seems to work with out issue on my device.

**Comment by gfodor** [comment] 2020-01-11 00:07
can confirm the v7 apk does not work either. 

tried headphones, guess what, it works with headphones! i don't think it's hardware related, since it's perfectly reproducable for me each session, and its triggered when i accept mic permissions (at which point we open the mic stream.) so I bet the underlying system somewhere is breaking the stream to the hardware speakers.

it's really weird. when using the headphones, i still hear the volume dip out for 1-3 seconds, but then it recovers. in speaker mode, the dip happens, and instead of the volume rebounding, it just goes silent.

**Comment by gfodor** [comment] 2020-01-11 00:09
i think i'd be OK with us pausing this issue pending another reproduction. it's pretty fatal, so i suspect we'll hear about it happening in the wild. i do put a small probability that there's *some* hardware issue going on here (perhaps not directly related to the speakers) given the fact the headphones work.

**Closed** 2020-06-08 14:20 UTC
Labels: bug
