### ISSUE TITLE
The background wrongly remains dimmed after resuming the app

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3226] opened 2020-04-23 09:16 UTC
**[Affected Versions]:**
- Firefox Reality version 10 RC1 (6db2f60a)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Open a library so that the background gets dimmed.
2. Press the Pico/Vive/Oculus button on the controller.
3. Quit the app (except Oculus).
3. Reopen the FxR app (on Oculus click the Resume button).
4. Dismiss the library and observe the background.

**[Expected results]:**
- The background switches back to normal.

**[Actual results]:**
- The background remains dimmed..

**[Notes]:**
- This issue is reproducible with all scenarios (having prompts opened, Private Browsing) where the background is dimmed.
- Attached a screen recording of the issue: [link](https://drive.google.com/open?id=1oApLxC-0Pwmqku_hbwmlm6ANdlQeihGM).

**Comment by keianhzo** [comment] 2020-04-23 09:56
Same root cause as https://github.com/MozillaReality/FirefoxReality/issues/3222.

Closed by https://github.com/MozillaReality/FirefoxReality/pull/3224

**Closed by keianhzo** 2020-04-23 09:56 UTC
Labels: [QA]:Normal issue, regression

**Comment by Softvision-RemusDranca** [comment] 2020-04-27 09:30
I have verified this issue and it's no longer reproducible with the Firefox Reality version 10 RC2 (17a313b). The background is now switched back to normal when dismissing the libraries after quiting and resuming the app.

Tested on HTC Vive Focus (Android 7.1.2), Oculus Quest (Android 7.1.1) and Pico Neo 2 (Android - 8.1.0) devices.
