### ISSUE TITLE
The app crashes while navigating on Youtube website

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1658] opened 2019-08-26 14:09 UTC
**[Affected Versions]:**
- Firefox Reality 1.4-32352315 (08.23.2019)

**[Affected Platforms]:**
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32352315 (08.23.2019) apk. installed.
- The headset is turned on.

**[Steps to reproduce]:**
1. Open the app.
2. Open a recommended video from Youtube.
3. Scroll through the page and play a second video.
4. Observe the behavior.

**[Expected results]:**
- The websites is correctly scrolled/navigated.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1wcith9XiF1Jmc9hrGVXrDx6Byi2ilEA_) 
- Also, here is the [logcat](https://drive.google.com/open?id=1rADbb0-28y-E4jsMeX1aRXHzjKQMCMq3) recorded while reproducing this issue.

**Comment by bluemarvin** [comment] 2019-09-03 22:52
https://bugzilla.mozilla.org/show_bug.cgi?id=1576746

**Comment by bluemarvin** [comment] 2019-09-20 00:13
@Softvision-RemusDranca I've spent the day trying to reproduce this crash with the latest version and have tried on a Pixel 2, Oculus Go, and Oculus Quest and have not been able to reproduce. Can you test again to see if you can still reproduce on the latest staging builds?  Some one from the Gecko graphics team who is trying to fix the issue has also tried to reproduce the issue with out success which makes fixing it a challenge.

**Comment by Softvision-RemusDranca** [comment] 2019-09-20 12:16
I have some bad news, I reproduced the issue on the Oculus Quest, Oculus GO and HTC Vive Focus Plus devices using the latest 1.5-32622233 (cfdab616) build.
However, the time until the app crashed is longer than before.
Here are the crash reports and logcats, hopefully they'll give more insight: 
- Oculus Quest:
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/8b789382-0f6e-40ad-a7e7-8346d0190920)
	- Logcat: [link](https://drive.google.com/open?id=1ceVCzVBVB0EdwsqhEQC36ikEIZb0AU4T)
 - Oculus GO:
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/043c5db4-d840-4dc2-ae5e-1f1cd0190920)
	- Logcat: [link](https://drive.google.com/open?id=1GbZBR4qy9V5k8i2ewB8TdCFMGTRb_VUf)
- HTC Vive Focus Plus:
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/28ebe224-e4cc-4528-aca3-5f43b0190920)
	- Logcat: [link](https://drive.google.com/open?id=1RBxJi8hotxDJvP7Ga8fVWiBzpy9JSvgk)

**Comment by bluemarvin** [comment] 2019-09-20 16:23
@Softvision-RemusDranca I didn't expect it to be fixed but wanted to know if you could still reproduce it. I think the next step is to create a special build with extra instrumentation around the crash site to try and capture more diagnostic information in the log. Then if you could reproduce the crash that might give us enough information to make a speculative fix for the bug. We've had three different people trying to recreate the crash with out success unfortunately.

**Comment by bluemarvin** [comment] 2019-10-11 16:05
The fix for this landed in GV 71.0.20191011093010

**Comment by bluemarvin** [comment] 2019-10-11 16:12
Since the fix has landed in GeckoView so late into the testing cycle, we will wait to update GeckoView until v6.

**Comment by MortimerGoro** [comment] 2019-10-14 15:14
Fixed in #1962

**Closed by MortimerGoro** 2019-10-14 15:14 UTC
Labels: Bugzilla, [QA]:Blocker issue, blocked, bug, crash 🔥
