### ISSUE TITLE
The text next to the drag-handles can not be selected if clicking too close to them

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2379] opened 2019-11-26 16:15 UTC
**[Affected Versions]:**
- Firefox Reality version 7 RC3 (7b66fb14)
- Firefox Reality version 7-3330142 (7c4caf46)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2 
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**
1. Open a webpage containing text.
2. Long click on a word to select it.
3. Long click on the right part of the word next to the selected one.
4. Observe the behavior.

**[Expected results]:**
- The words next to the selected text can be selected by clicking on them.

**[Actual results]:**
-  The words next to the selected text can not be selected.

**[Notes]:**
- There is a region of ~5 characters from the edges of a selected text where selecting other characters is not possible.
- The issue is reproducible for input fields as well.
- This issue is reproducible on Firefox Preview.
- This issue is not reproducible on Chrome for Android.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1PiQ2FN1CfWJa60KtcH7BjOHneD743tCl/view?usp=sharing).

**Comment by keianhzo** [comment] 2019-12-02 10:24
This seems to be the expected behavior in GV, there seems to be some sort of safe area around the selection maybe to avoid issues with touch devices and the handles.

**Comment by keianhzo** [comment] 2020-01-08 15:32
Closing as I have confirmed that this is the expected bahavior.

**Closed by keianhzo** 2020-01-08 15:32 UTC
Labels: [QA]:Normal issue
