### ISSUE TITLE
A key remains in a hover state after moving the pointer away while the Move/Close button are hovered with the second controller

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3027] opened 2020-03-23 10:22 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140822127 (fb72e3a)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Both controllers are active.

**[Steps to reproduce]:**
1. Click the Awesomebar do display the keyboard. 
2. Hover over a key using a controller.
3. Using the second controller hover over the controller's Move/Close button.
4. Move the first controller from the keyboard.
5. Observe the hovered key.

**[Expected results]:**
- The hover state is dismissed.

**[Actual results]:**
- The key remains in a hover state.

**[Notes]:**
- The key's hover state is dismissed after hovering the keyboard with the same controller or after closing and reopening the keyboard.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1y_1DOS6B8DjtwwAjfHRhrHObkIanSeK1).

**Comment by keianhzo** [comment] 2020-04-04 07:43
Possible duplicate of https://github.com/MozillaReality/FirefoxReality/issues/3004

**Comment by Softvision-RemusDranca** [comment] 2020-05-12 14:14
It seems that this issue is now reproducible with the numeric keyboard as well. A numeric key remains in a hover state after moving the pointer on the normal keyboard while having the other controller pointing over the normal keyboard. [Here](https://drive.google.com/open?id=1RLOB2UYz9TMBPvEY0eKqiuzGOUZNcNB4) is a screen recording of this behavior.
The key remains in a hover state even after closing and reopening the keyboard but dismissed if it's hovered again.

Tested on Pico Neo2 - Android 8.1.0 and Oculus Quest - Android 7.1.1 using the Firefox Reality version 10 RC5 (e84d3c9) build.

**Closed** 2024-07-22 11:47 UTC
Labels: [QA]:Minor issue, ARCHIVED
