### ISSUE TITLE
[Keyboard: Thai] The language name on the spacebar is not displayed in its native language

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3625] opened 2020-07-06 11:14 UTC
**[Affected Versions]:**
- Firefox Reality version 11 RC3 (f6453025)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Click inside the awesomebar.
2. Change the keyboard language to Thai.
3. Observe the spacebar.

**[Expected results]:**
- The language name on the spacebar is displayed in its native language.

**[Actual results]:**
- The language name on the spacebar is displayed in English.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1k660hcFmC69R03Wj-StPXYCjoHa_YzuS/view?usp=sharing).

**Comment by keianhzo** [comment] 2020-07-06 13:26
Duplicate of #3624 We don't have Thai translations in the app yet so they "Thai" tag is not going to get translations anywhere in the app including the spacebar or the language menu.

**Closed** 2024-07-22 11:46 UTC
Labels: [QA]:Minor issue, [QA]:Caught_by_testsuite, ARCHIVED
