### ISSUE TITLE
Default search engine choice

### ISSUE THREAD

**Issue by SeburoSUMO** [MozillaReality/FirefoxReality#3436] opened 2020-05-28 19:05 UTC
**Is your feature request related to a problem? Please describe.**
Currently, FxR only searches with Google from the address bar.

**Describe the solution you'd like**
In line with other Firefox's (both desktop and mobile), the ability to choose the default search engine for searches from the address bar, with potentially a list of preselected search tools to choose from (Google, Qwant, DuckDuckGo and others) in the settings of FxR.

**Describe alternatives you've considered**
Users could manually set a bookmark (or have one they have synced across using Firefox Sync) to a search tool they would prefer to use.  This would not be embedded in the browser search bar so it would not be as easy to use from any other page the user is browsing.

**Additional context**
Screenshot of the Firefox Preview Nightly default search engine choices.  For Fxr, this could be tailored to MR content, such as including YouTube.

![Screenshot_1590692007979](https://user-images.githubusercontent.com/31939113/83182377-2cbe9600-a11e-11ea-94fe-0eb6903da7e5.jpg)

**Comment by bluemarvin** [comment] 2020-05-28 19:14
Dupe of https://github.com/MozillaReality/FirefoxReality/issues/292

Currently FxR selects the search engine base on the users region.

@emstanley We should add #232 to our road map.

**Closed by bluemarvin** 2020-05-28 19:14 UTC
Labels: duplicate
