### ISSUE TITLE
Browser resize reset fails when in a portrait mode

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#129] opened 2018-07-11 13:56 UTC
Steps:
- Go into manual resize mode.
- Stretch window so it is taller.
- Exit focus mode.

**Expected result**: Window returns to default size.
**Actual result**: Window stays tall while content resizes and gets stretched.

Also, when in resize mode after a manual resize, clicking the 1x button doesn't change the height of the window and it stay tall.

**Comment by bluemarvin** [comment] 2018-07-11 15:43
duplicate of #108

**Closed** 2018-07-11 15:59 UTC
Labels: bug, duplicate
