### ISSUE TITLE
The wrong tooltip is displayed for the user agent button after requesting the desktop site

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1719] opened 2019-08-30 13:50 UTC
**[Affected Versions]:**
- Firefox Reality 1.4-32420004 (RC1)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following website: facebook.com
2. Click the switch user agent button.
3. Hover over the switch user agent button.
4. Observe the tooltip displayed.

**[Expected results]:**
- The "Request mobile site" tooltip is displayed.

**[Actual results]:**
- The "Request desktop site" tooltip is displayed.

**[Notes]:**
- Attached a screen capture of the issue.
![Fri08-30-2019_15-48-27 91](https://user-images.githubusercontent.com/51400741/64025792-27f49380-cb46-11e9-892c-9984340ddb41.png)

**Comment by bluemarvin** [comment] 2019-08-30 15:42
This tooltip is by design. I agree this is confusing. @jvonitter I think we need to revisit how this feature works. I also find its interaction with the settings preference to be confusing.

**Comment by jvonitter** [comment] 2019-09-03 22:20
This is going to change when we do tabs and FxA. Leaving this open for now but not pulling it in to 1.4 or 1.5

**Comment by jvonitter** [comment] 2019-10-02 23:51
will be fixed by #1898

**Closed by jvonitter** 2019-10-02 23:51 UTC
Labels: [QA]:Minor issue
