### ISSUE TITLE
Back button should be able to interrupt page load (act immediately)

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#534] opened 2018-09-17 19:26 UTC
## Hardware

Oculus Go

## Steps to Reproduce

1. Press Back button during page load
2. Note that it appears that Back request is not respected until page is fully loaded

## Current Behavior

1. Press Back button during page load
2. Note that it appears that Back request is not respected until page is fully loaded

## Expected Behavior

Pressing Back button during page loads should be immediately respected, and abort loading and go back.

## Possible Solution

Pressing Back button during page loads should be immediately respected, and abort loading and go back.

```
```

</details>

**Comment by keianhzo** [comment] 2018-09-17 20:44
This is actually affecting to any action that happens while a session is loading: back, forward, reload and home.

**Comment by cvan** [comment] 2018-09-18 06:41
This happened to me while I was waiting for https://www.thedart76.com/webvr/epic-medieval-battle/emb.html to load

**Comment by philip-lamb** [comment] 2019-03-09 03:06
Closing as duplicate of #682 as that bug has more info.

**Closed** 2019-03-09 03:06 UTC
Labels: P3, bug, duplicate
