### ISSUE TITLE
Different results using local viewerpose between FxR and Oculus

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#3435] opened 2020-05-28 16:59 UTC
I modified the jsfiddle in https://github.com/MozillaReality/FirefoxReality/issues/3412 to use local reference space instead of viewer. Also removed the randoms to set something fixed to make the comparisons easier
https://jsfiddle.net/rxLh6qez/

I see different results between FxR and Oculus:
- The cube is above your head in Oculus but way higher in FxR.

**Comment by daoshengmu** [comment] 2020-05-29 01:12
The jsfiddle link can't show VR Button for me in Oculus Browser. So, I can't compare it with FxR.
I made a similar sample as [1], but I can't reproduce the probem between OB and FxR.

]https://gist.github.com/daoshengmu/e9a36876a8d2e2812af4ae6f2649eea2

**Comment by daoshengmu** [comment] 2020-05-29 23:33
Bugzilla patch is here, https://bugzilla.mozilla.org/show_bug.cgi?id=1642019

**Comment by bluemarvin** [comment] 2020-06-26 00:30
@MortimerGoro and @daoshengmu Is this fixed now? Please close if no longer an issue.

**Comment by daoshengmu** [comment] 2020-06-26 00:39
Based on our previous discussion, I remembered that was a bug from Oculus. We are correctly following the spec.

**Comment by bluemarvin** [comment] 2020-06-26 00:44
Then we should close this and report the issue to oculus.

**Closed** 2024-07-22 11:47 UTC
Labels: Bugzilla, ARCHIVED
