### ISSUE TITLE
Taking on and off the Pico G2 headset causes a swimming, dragging effect requiring manual reorientation

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1020] opened 2019-03-15 10:12 UTC
## Hardware
Pico G2
(Not reproducible with Oculus Go.)

## Steps to Reproduce
1. Launch FxR
2. Look around with your head
3. Take the headset off, move your head in a different direction, and put the headset back on
4. Notice the complete experience (browser and all) does a drag to try to reorientation 
5. Notice you must press the Pico button on the controller to readjust your orientation to get your return to the orientation you expected before you put your headset down

## Current Behavior
Orientation gets affected upon taking the headset on, off, and repeat. You correct the browser and window to where you where you left off it, you must press the Pico button on the controller to readjust your orientation to get your display to return to its expected spot.

This issue I have not been able to reproduce this exact effect. The fading-in effect can cause confusion, but I've never had to so consistently (90%) of the time in FxR on Pico G2 cause such a user to manually re-orient.

I tried in various other apps, including Viveport's stock apps such as the Browser: I could not reproduce the same effect as in FxR.

## Expected Behavior
Taking the Pico G2 headset on and off should not (as jarringly) adjust your orientation and require pressing the Pico button the controller to reset the orientation manually (which is admittedly an unintuitive step to identify and act on).

**Comment by philip-lamb** [comment] 2019-03-18 03:19
I'm not able to reproduce this on the Vive Focus.

**Comment by cvan** [comment] 2019-03-18 23:29
> I'm not able to reproduce this on the Vive Focus.

Thanks - yeah, I cannot either. I'm quite sure this is specific to the Pico devices.

**Comment by bluemarvin** [comment] 2019-04-12 22:26
I compared the events between the Focus and the G2 and the G2 is not doing an auto-recenter when resumed like the Focus does. This looks like a platform bug. I could work around it but would prefer they fix it.

**Comment by bluemarvin** [comment] 2020-06-02 20:32
Closing since we now have native support of Pico devices.

**Closed by bluemarvin** 2020-06-02 20:32 UTC
Labels: P3, UX, perf, platform:WaveVR
