### ISSUE TITLE
Poor rendering of detail in WebVR scenes

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#937] opened 2019-02-05 07:22 UTC
## Hardware
Oculus Go

## Steps to Reproduce
1. Load http://pano.yfway.com/30801042 or a demo from the [krapno's WebVR example](https://krpano.com/webvr/) in Firefox Reality.
2. Navigate to other panos by the gazing on a hotspot, and move your head around to notice the tracking is a bit slow.
4. Open the same site in Oculus Browser.
5. Upon navigating to other panos, notice the tracking is more stable than it is in Firefox Reality.

Originally reported in the [krpano forums](https://krpano.com/forum/wbb/index.php?page=Thread&postID=77699).

## Current Behavior
The tracking is laggy in [krpano-powered WebVR galleries](https://krpano.com/webvr/).

## Expected Behavior
The tracking is not laggy in [krpano-powered WebVR galleries](https://krpano.com/webvr/).

## Context
Originally reported in the [krpano forums](https://krpano.com/forum/wbb/index.php?page=Thread&postID=77699).

**Comment by ScottWitte** [comment] 2019-02-05 22:37
I originally reported this problem on the KRPano forum. The biggest issue for me is that the rendering quality is worse in FFR than in Oculus browser. Look at any area with detail such as text. FFR seems to have half the resolution as Oculus Browser.

As for laggy behavior, might that actually be the result of a lower frame rate in FFR?

My test example is https://www.tourdeforce360.com/grandtheater/vtour.html. In the opening scene look at the sign just to the right. It is almost readable in Oculus Browser, definitely not in FFR.

**Comment by cvan** [comment] 2019-02-06 02:43
@ScottWitte: I don't notice the resolution difference because I cannot get the page to load in Firefox Reality. when I load the [Grande Theater tour](https://www.tourdeforce360.com/grandtheater/vtour.html), I receive a `Secure Connection Failed` error (still investigating).

## Firefox
![image](https://user-images.githubusercontent.com/203725/52317045-2af22180-2973-11e9-8da3-277688bb54c7.png)

## Oculus
![image](https://user-images.githubusercontent.com/203725/52317658-c2f10a80-2975-11e9-9a32-0dc677a9e462.png)
![image](https://user-images.githubusercontent.com/203725/52317682-e87e1400-2975-11e9-9432-a7dfa2665e95.png)
![image](https://user-images.githubusercontent.com/203725/52317695-f16ee580-2975-11e9-8693-7ca10a0b502c.png)

P.S. that tour is fantastic, btw. awesome visuals.

**Comment by cvan** [comment] 2019-02-06 03:02
Following up, it looks like the HTTPS cert for https://www.tourdeforce360.com is marked as invalid by Firefox's security policy: https://observatory.mozilla.org/analyze/www.tourdeforce360.com#tls

I tried a few [other tourdeforce360.com pano tours](https://www.google.com/search?q=site%3Awww.tourdeforce360.com+vtour.html&oq=site%3Awww.tourdeforce360.com+vtour.html). outstanding photos and resolution, but I could view only in Fullscreen, since they're not using the krpano + WebVR plugin.

**Comment by ScottWitte** [comment] 2019-02-06 05:19
Christopher,

Thanks for the SSL issue heads up. I haven't seen that on any Mozilla browser I have tested on multiple platforms. Nor is it a problem in FFR on my Go. Needs to be looked into, for sure.

Anyway, you can just use http instead of https and that should allow the site to display.

And yes, very little of the regular site is VR ready. Lots to do before that can happen.

**Comment by philip-lamb** [comment] 2019-05-09 05:40
@cvan I think they resolved to push updates to their WebVR player. Do we want to keep tracking this or close it out?

**Comment by ScottWitte** [comment] 2019-05-09 20:41
@philip-lamb, I see no improvement in the current browser. Are we sure the fix is integrated? When will it be rolled out?

BTW, I believe we resolved the SSL problem. Anyone who wants to do the comparison can use the above example.

**Comment by philip-lamb** [comment] 2019-05-16 22:31
We do seem to be less sharp in the theater tour. Will hold over for further investigation.

**Comment by cvan** [comment] 2019-05-21 11:00
> @cvan I think they resolved to push updates to their WebVR player. Do we want to keep tracking this or close it out?

This is still reproducible with krpano 1.19-pr16 (2018-04-04) and krpano 1.19-pr15 (2018-03-28). Was there a new krpano version rolled out?

**Comment by ScottWitte** [comment] 2019-05-21 14:31
We expect a new version "shortly." However, the problem isn't with KRPano. It works fine in all other browsers so the likely issue is with FFR.

**Closed** 2019-06-05 18:07 UTC
Labels: P3, WebVR, compatibility, needinfo, perf
