### ISSUE TITLE
Keyboard stays open after entering a URL

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#860] opened 2018-11-27 22:52 UTC
## Hardware
Oculus Go
9cf66ae

## Steps to Reproduce

1. Press the URL bar
2. Enter an address
3. Notice the URL bar stays open even after the page is loaded

## Current Behavior
The URL bar remains upon after a URL is entered / a page is requested.

## Expected Behavior
The URL bar closes after a URL is entered / a page is requested.

## Context
Not sure if this is a regression I added in PR #830. I haven't dug deep enough yet.

**Comment by keianhzo** [comment] 2018-11-29 20:08
Probably related or duplicate of #846

**Comment by cvan** [comment] 2018-11-29 20:36
Yep, I notice it after a crash prompt, search suggestions, and a few others. Probably the same fix for all?

**Comment by keianhzo** [comment] 2018-12-18 14:53
Fixed with ##889 Closing

**Closed by keianhzo** 2018-12-18 14:53 UTC
Labels: P4, bug, in progress, regression
