### ISSUE TITLE
Page loading error when entering New York Times

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#217] opened 2018-07-19 23:33 UTC
Hardware: Oculus Go
Steps to Reproduce: Type 'nytimes.com'
Actual Behavior: loading error message appears
Expected Behavior: go to NYT website
Recommendation: N/A

More context from our usability engineer who found the issue: 
A quick question—I would like to have users sign in to a New York Times account (to have an excuse to make them type in some weird characters). We have the account set up, and when we enter the information NYT accepts it (does not give an error message like it does when we mis-enter the information), but the browser just gives us a loading message and stays there. We’re not having any issues with the WiFi on our side and can easily sign in on other devices. We haven’t seen the same issue with other sites. Could this be a bug of some kind?

**Comment by cvan** [comment] 2018-07-20 21:07
I just tried to reproduce. For you/them, Is the rest of the UI responsive? My cursor frozen at a particular point on the page. Do you have a screenshot or video or numbered steps to reproduce in the `Steps to Reproduce` part. I'm a tad confused. Thanks!

**Comment by thenadj** [comment] 2018-07-20 23:17
I'll ask them for more context. I am not able to reproduce it, so it might be something on their end. I'll post more info to this card as soon as I have it.

**Comment by thenadj** [comment] 2018-07-20 23:47
Here is what they said:

I was using an Oculus Go and was not charging or tethered.

I went to the New York Times site from the link on the Firefox VR landing page. The site loaded with no problems. Then I clicked on  the “sign in” link in the top right-hand corner of the page. I was given a sign-in screen with fields for username and password. I entered my username and password and clicked the submit button. There the screen showed a “loading” state (I believe everything was greyed out and something was swirling) but the content never loaded.

I closed out and tried signing in again. This time I mistyped my password and received a red outline around the input field and an error warning. I retyped the password, this time correctly, clicked submit, and got stuck at the same loading screen. I waited for several minutes and nothing happened.

Someone else in the office also tried, following the same steps as above, and experienced the same thing.

I tried signing into my NYT account via both my computer and my phone and had no issues. I haven’t been able to try again on the Oculus Go due to working at home (apologies).

**Comment by avrignaud** [comment] 2018-07-21 14:57
@nancyhang Can we prioritize this for Wednesday? Blink wants to use signing into the NYT with special characters as a test.

**Comment by keianhzo** [comment] 2018-07-24 16:17
@avrignaud @nancyhang @bluemarvin  I have taken a look at this and this might be related to the fact that we have the tracking protection enabled by default in FxR.

I only managed to reproduce this using a username/password for the logging, any other login method works fine. Apparently has to do with a captcha that NYT is using for that login method and that tracking protection is blocking.

`07-24 18:05:17.023 14499-14519/org.mozilla.vrbrowser D/GeckoViewProgress: onSecurityChange
07-24 18:05:17.024 14499-14519/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: "The resource at “https://www.google.com/recaptcha/api.js?onload=reCaptchaOnLoadCallback&render=explicit” was blocked because tracking protection is enabled." {file: "https://myaccount.nytimes.com/auth/login?URI=https%3A%2F%2Fwww.nytimes.com%2F" line: 0}]
07-24 18:05:17.027 14499-14519/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: "Loading failed for the <script> with source “https://www.google.com/recaptcha/api.js?onload=reCaptchaOnLoadCallback&render=explicit”." {file: "https://myaccount.nytimes.com/auth/login?URI=https%3A%2F%2Fwww.nytimes.com%2F" line: 1}]
`

**Comment by avrignaud** [comment] 2018-07-24 16:30
@larsbergstrom Thoughts on whether we can/should turn off tracking protecting temporarily - or even just this site for Wednesday's build for Blink?

**Comment by bluemarvin** [comment] 2018-07-24 19:29
I have a fix for this.

**Comment by avrignaud** [comment] 2018-07-26 15:06
Issues still remain with login, please see below from Blink UX:

```Issues with signing in to New York Times:

Teresa clicked on the sign-in link for the NYT and entered the correct email address and password. She was taken to a screen that showed a bunch of tiles, each with a different picture—but no instructions. After some confusion and refreshing, the full view loaded and we discovered that if she scrolled up a bit there was instructions for her to select all the images that contained a boat. She tried to select the right boxes but was unable to (it seemed like the site was not registering her clicks). When she tried to click the back button on the control an image would randomly select instead. She wasn’t able to complete this task and we decided to abandon the attempt. ```

**Comment by bluemarvin** [comment] 2018-07-26 15:30
I just did a clean install of the latest code on my Go and had no problem logging into the NYT site. Their login is pretty terrible and the use of the Google recaptcha makes things hard even on a regular phone. Part of the issue is the recapcha is tall for a phone screen and the top and bottom are cut off in FxR requiring scrolling to see the whole thing.

**Comment by nancyhang** [comment] 2018-07-26 16:52
@avrignaud can we get someone from Blink to try this again with the latest build?

**Comment by keianhzo** [comment] 2018-07-30 16:07
It's working fine for me too, although I still can see some captcha related errors logs in the console:

`07-30 18:01:30.854 6959-6979/org.mozilla.vrbrowser E/GeckoConsole: [JavaScript Error: "NS_BINDING_ABORTED: " {file: "https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=v1531759913576" line: 1}]`

```
07-30 18:01:30.598 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress[C]: ProgressTracker onProgressChangeUpdate {"prev":10.000057220458984,"uri":"https://www.nytimes.com/?login=email&auth=login-email","locationChange":true,"pageStart":true,"pageStop":false,"firstPaint":true,"pageShow":false,"parsed":false,"totalReceived":1,"totalExpected":1} 1/1 progress=35.000057220458984
07-30 18:01:30.606 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress[C]: onProgressChange 0/0 61853/61853
07-30 18:01:30.607 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress[C]: ProgressTracker handleProgress null 61853/61853
07-30 18:01:30.608 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress[C]: ProgressTracker updateProgress
07-30 18:01:30.610 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress[C]: ProgressTracker onProgressChangeUpdate {"prev":35.000057220458984,"uri":"https://www.nytimes.com/?login=email&auth=login-email","locationChange":true,"pageStart":true,"pageStop":false,"firstPaint":true,"pageShow":false,"parsed":false,"totalReceived":61854,"totalExpected":61854} 61854/61854 progress=38.53931427001953
07-30 18:01:30.733 6959-7109/org.mozilla.vrbrowser I/UtilPoller: GPU Util 0.551880 / CPU Util 0.810000 (avg 0.764812)
07-30 18:01:30.782 6959-6979/org.mozilla.vrbrowser D/GeckoViewTrackingProtection: onSecurityChange
07-30 18:01:30.782 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress: onSecurityChange
07-30 18:01:30.795 6959-6979/org.mozilla.vrbrowser D/GeckoViewContent[C]: handleEvent: DOMTitleChanged
07-30 18:01:30.802 6959-6959/org.mozilla.vrbrowser E/VRB: SessionStore onTitleChange
07-30 18:01:30.854 6959-6979/org.mozilla.vrbrowser E/GeckoConsole: [JavaScript Error: "NS_BINDING_ABORTED: " {file: "https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=v1531759913576" line: 1}]
07-30 18:01:30.861 6959-6979/org.mozilla.vrbrowser D/GeckoViewTrackingProtection: onSecurityChange
07-30 18:01:30.866 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress: onSecurityChange
07-30 18:01:30.871 6959-6979/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: "The resource at “https://www.googletagservices.com/tag/js/gpt.js” was blocked because tracking protection is enabled." {file: "https://www.nytimes.com/?login=email&auth=login-email" line: 0}]
07-30 18:01:30.876 6959-6959/org.mozilla.vrbrowser I/VRB: Blocking Ad: https://www.googletagservices.com/tag/js/gpt.js
07-30 18:01:30.893 6959-6959/org.mozilla.vrbrowser E/VRB: SessionStore onPageStop
07-30 18:01:30.900 6959-6979/org.mozilla.vrbrowser D/GeckoViewTrackingProtection: onSecurityChange
07-30 18:01:30.901 6959-6979/org.mozilla.vrbrowser D/GeckoViewProgress: onSecurityChange
07-30 18:01:30.901 6959-6979/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: "The resource at “https://www.googletagmanager.com/gtm.js?id=GTM-P528B3&gtm_auth=tfAzqo1rYDLgYhmTnSjPqw&gtm_preview=env-130&gtm_cookies_win=x” was blocked because tracking protection is enabled." {file: "https://www.nytimes.com/?login=email&auth=login-email" line: 0}]
07-30 18:01:30.910 6959-6959/org.mozilla.vrbrowser I/VRB: Blocking Ad: https://www.googletagmanager.com/gtm.js?id=GTM-P528B3&gtm_auth=tfAzqo1rYDLgYhmTnSjPqw&gtm_preview=env-130&gtm_cookies_win=x
07-30 18:01:30.913 6959-6979/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: "Loading failed for the <script> with source “https://www.googletagservices.com/tag/js/gpt.js”." {file: "https://www.nytimes.com/?login=email&auth=login-email" line: 56}]
07-30 18:01:31.008 6959-6979/org.mozilla.vrbrowser W/GeckoConsole: [JavaScript Warning: "Ignoring unsupported entryTypes: paint." {file: "https://www.nytimes.com/?login=email&auth=login-email" line: 181}]
```

The rest of the errors are related to Ad blocking as we are still blocking Ad, Social and Analytics.

**Comment by bluemarvin** [comment] 2018-08-22 18:47
I can log into NYT with out issue. If some one wants to add STR, I'll investigate.

**Comment by nancyhang** [comment] 2018-08-28 17:32
We can't seem to reproduce this issue.

**Closed** 2018-08-28 17:31 UTC
Labels: P0, bug
