### ISSUE TITLE
Connected to Hotel Wifi but Can't Get Login

### ISSUE THREAD

**Issue by daoshengmu** [MozillaReality/FirefoxReality#1303] opened 2019-06-06 05:12 UTC
## Hardware

Oculus Go using VR UA (I didn't check other UAs)

## Steps to Reproduce

1. Go to Oculus setting and choose the available Wifi to connect
2. Insert something at the FxR URL bar and click Go.
3. It should be redirected to Hotel's internet login page but not, it shows a no internet access blanket page.

## Current Behavior

it shows a no internet access blanket page and can't operate the login process. I have to use Oculus Browser to help me jump into the login page.

## Expected Behavior

It should be the same with OB to be redirected to the hotel's internet login page when connecting to the internet at the initial stage. 

## Context

It is annoying to me, in Oculus, we still can use OB to avoid this issue. If we wanna be a default browser, we would need to handle this kind of connection properly.

```
```

</details>

**Comment by philip-lamb** [comment] 2019-06-06 05:22
Duplicate of #938

**Closed by philip-lamb** 2019-06-06 05:22 UTC
