### ISSUE TITLE
The wrong headset controllers are displayed when entering VR on the “vr.with.in” website

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#1369] opened 2019-07-08 11:33 UTC
**[Affected Versions]:**
- Firefox Reality 1.2.3-131652030

**[Affected Platforms]:**
- Oculus Quest (Android 7.1.1)

**[Preconditions]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to the following website: [vr.with.in](https://vr.with.in/).
2. Click the "Enter VR" button.
3. Observe the controllers shown to the user.

**[Expected results]:**
- The Oculus Quest controllers are displayed.

**[Actual results]:**
- The Oculus Rift controllers are displayed.

**[Notes]:**
- The issue is also reproducible with the Oculus Browser.
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/15Mx3SqFOyUYLFbvwgIlgOOLCZcSUReg3/view?usp=sharing)

**Comment by bluemarvin** [comment] 2019-07-08 22:10
This is a web compat issue with the website. When in immersive mode, the web page is responsible for detecting and drawing the correct controller models. If an issue is reproducible in the Oculus Browser (as noted) it is a very good indication that it is a web compat issue and not necessarily a Firefox Reality issue.

**Comment by philip-lamb** [comment] 2019-07-08 22:14
I've contacted the with.in folks, and I'm going to go ahead and close this with 'invalid' since it's not our bug.

**Closed by philip-lamb** 2019-07-08 22:14 UTC
Labels: invalid
