### ISSUE TITLE
The homepage is opened when the app is resumed after exiting from immersive mode

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3543] opened 2020-06-24 15:38 UTC
**[Affected Versions]:**
- Firefox Reality version 11-141760226 - 71aabd05 (AC 44.0.0)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Play the "Hello WebXR" card from Interactive Experience.
2. Press the pico button on the controller.
3. Open the app again and observe the behavior.

**[Expected results]:**
- The "Hello WebXR" website is loaded in normal browsing.

**[Actual results]:**
- The "Hello WebXR" website is briefly shown and the FxR homepage is loaded.

**[Notes]:**
- If the navigate ”Back” button is clicked the "Hello WebXR" website is loaded.
- The issue is reproducible with 360 videos as well.
- The issue is always reproducible on the Pico G2 4K.
- The issue is intermittently reproducible on the Pico Neo2 and the HTC Vive Focus Plus headsets, it is not reproducible with the babylonjs examples.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Ptl6q-j80GqUv7uutT6bdo67Uq04Pi4z/view?usp=sharing).

**Comment by bluemarvin** [comment] 2020-06-24 20:43
After investigating, I believe this is a dupe of #3530
This should only happen when the window was not restored from a previous session.

**Closed** 2020-06-26 12:36 UTC
Labels: [QA]:Caught_by_exploratory, [QA]:Normal issue, duplicate

**Comment by Softvision-GeluHaiduc** [comment] 2020-07-01 09:27
I have verified this issue with Firefox Reality version 11 RC2 (5fd1bfd0) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the homepage is not opened when the app is resumed after exiting from immersive mode, the correct windows are restored.
