### ISSUE TITLE
The inactive window controls are briefly gaining a hover effect when the active window controls are clicked

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2650] opened 2020-01-15 14:02 UTC
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure to have 2 windows opened.
- Make sure the windows are of different sizes. (this is necessary to better see the issue)

**[Steps to reproduce]:**
1. Click on one of the window controls "<" or ">" of an active window.
2. Observe the inactive window controls.

**[Expected results]:**
- The inactive window controls UI is not changed.

**[Actual results]:**
- The "<" or ">" inactive window controls UI are briefly gaining a hover effect.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1LZBy4kR2RRuwNf68Nrahj_3lHVXq9Ptj).

**Comment by bluemarvin** [comment] 2020-02-12 18:12
I think this is caused by the controls moving with the window? @keianhzo?

**Comment by keianhzo** [comment] 2020-02-17 11:24
I can't reproduce this anymore in master. Can you @Softvision-GeluHaiduc confirm that this is still happening?

**Comment by Softvision-GeluHaiduc** [comment] 2020-02-17 12:53
Using the latest RC, Firefox Reality version 9 RC1 (33f6c4d8), I couldn’t reproduce this issue.

**Comment by keianhzo** [comment] 2020-02-17 14:59
Ok, I'll close this one. You can reopen if you see this behavior again.

**Closed by keianhzo** 2020-02-17 14:59 UTC
Labels: [QA]:Minor issue, regression
