### ISSUE TITLE
Implement UI to allow users to share voice data with Mozilla

### ISSUE THREAD

**Issue by avrignaud** [MozillaReality/FirefoxReality#492] opened 2018-09-08 16:25 UTC
Mozilla would like (with user permission) to collect and process anonymous user voice samples to improve our voice recognition models. In order to do so we need to implement UI to explain to users what we will do with their voice, and allow them to opt in (and opt-out later if they change their mind).

Possible UI needs include:
- A button in settings that turns on/off sending voice data to Mozilla (default off)
- a way to prompt user the first time they try the voice icon to agree to sending voice data to Mozilla to improve our services - and explain that they can continue to use voice search even if they do not wish to share data with us

**Comment by cvan** [comment] 2018-09-18 06:46
I would suggest linking to https://voice.mozilla.org/ for more information about the Common Voice project. And to Contribute, here: https://voice.mozilla.org/speak

Agreed that Settings should be added - good idea :+1:

**Comment by avrignaud** [comment] 2018-11-02 21:21
@thenadj We need a design for this. Will be targeting 1.1.1.

**Comment by caseyyee** [comment] 2018-11-27 19:01
Needs to be considered as part of dialogue UX patterns along with https://github.com/MozillaReality/FirefoxReality/issues/641

**Comment by philip-lamb** [comment] 2019-05-17 00:48
Duplicate of #641. Forwarding there.

**Closed by philip-lamb** 2019-05-17 00:48 UTC
Labels: Needs Design, P3, UX
