### ISSUE TITLE
Amazon Prime Video does not load

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#744] opened 2018-11-09 23:38 UTC
## Hardware
Oculus Go
1.0.1, 5eeebbe

## Steps to Reproduce
0. Ensure you have an Amazon Prime Account (in order to watch Amazon Prime Videos)
1. Go to https://amazon.com/video and sign in, if you aren't signed in already
2. Navigate to https://www.amazon.com/gp/video/detail/B078GZXLM9/

## Current Behavior
**[Here's a full video (shown in order: Desktop, VR, Mobile).](https://drive.google.com/file/d/17njcor7mFoYZ79vfQ68cgXWd8nyQC5Ux/view?usp=sharing)**

### For Desktop
![image](https://user-images.githubusercontent.com/203725/47928852-a334dc80-de84-11e8-93f5-2cea431ea888.png)

![image](https://user-images.githubusercontent.com/203725/47929009-10e10880-de85-11e8-97e8-75f6635f47bb.png)
![image](https://user-images.githubusercontent.com/203725/47929010-12aacc00-de85-11e8-9489-75b536ecf3fd.png)
![image](https://user-images.githubusercontent.com/203725/47929012-13dbf900-de85-11e8-8593-525d8f54ebb0.png)
![image](https://user-images.githubusercontent.com/203725/47929016-14748f80-de85-11e8-9578-d7f1ad0cf9c5.png)
![image](https://user-images.githubusercontent.com/203725/47929018-15a5bc80-de85-11e8-890d-ae0972a5b226.png)

Upon clicking the Play button, it appears that the video begins to play but then a Video Unavailable window pops up.

### For (Mobile) _VR_ & _Mobile_
![image](https://user-images.githubusercontent.com/203725/47928810-80a2c380-de84-11e8-91f9-bbf44eb1723f.png)

Upon clicking the Play button, you are redirected to this URL: `intent://watch.amazon.com/watch?contentType=Movie&asin=B078GY1HJV&territory=US&ref_=dv_web_dp_mv_play_feature#Intent;scheme=https;package=com.amazon.avod.thirdpartyclient;end`

The site thinks we're on an Android phone/tablet. So it's trying to deep-link us to the Prime Video native Android app and launch the video there to play.

## Expected Behavior
Videos load.

## Possible Solution
Determine issues and, if possible, allow Amazon Prime videos to be loaded.

- Do what we (GeckoView and/or Media teams on Gecko) can do.
- Involve WebCompat folks.

## Context
Originally reported these findings to this WebCompat issue reported by a user from Firefox Reality's `Report an issue` button in the `Settings`: https://github.com/webcompat/web-bugs/issues/19322#issuecomment-435443368

## Error Logs and Stack Traces
(See screenshots above.)

**Comment by philip-lamb** [comment] 2019-02-27 08:50
Prime Video is Widevine DRM encoded. Closing this as duplicate of #967.

**Closed by philip-lamb** 2019-02-27 08:50 UTC
Labels: P1, bug, compatibility, question
