### ISSUE TITLE
Enter VR button just going to fullscreen/video, not immersive

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#1926] opened 2019-10-07 18:16 UTC
## Configuration

Firefox Reality version: 1.4.1
Firefox Reality build ID: 

Hardware: HTC Vive Focus Plus

## Steps to Reproduce

1. Load a WebVR site (tried on both a Hubs room and the "anime UI" example https://aframe.io/examples/ )
2. Click the button to enter VR

## Current Behavior

The experience goes full-screen mode, but stays 2D.

## Expected Behavior

Immersive, wrap-around 3D.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment] 2019-10-07 19:57
@larsbergstrom Can get a screen shot of `about:support`? I was able to reproduce the issue once, but after uninstalling 1.4.1 then running the update from the Vive store, immersive mode works. Also, are you able to see the controllers in FxR?

**Comment by bluemarvin** [comment] 2019-10-07 20:16
Actually, never mind. I don't think the Gecko version is the issue.

**Comment by bluemarvin** [comment] 2019-10-07 20:25
@larsbergstrom Is this issue 100% reproducible for you? I see very sporadically (twice) but have not found a way to reliably reproduce the issue.

**Comment by larsbergstrom** [comment] 2019-10-07 20:29
@bluemarvin I've mainly seen it when the first thing that I load is a very complicated Hubs scene (like the meetups). Otherwise, it's also very intermittent for me. It's gotten into that state for the last 2-3 meetups now, and only when they were in a pretty complicated room.

**Comment by larsbergstrom** [comment] 2019-10-07 20:46
Yes! That sounds right - killing FxR and re-starting does let the "Anime UI" work again.

**Comment by philip-lamb** [comment] 2019-10-08 03:03
Appears to be a duplicate of https://github.com/MozillaReality/FirefoxReality/issues/1777

**Comment by bluemarvin** [comment] 2019-10-08 03:23
This is actually a different issue because the VR display exists but fails to go into immersive mode. With #1777 there aren’t any VR displays to even attempt to enter immersive mode and a page reload fixes the issue.

**Comment by MortimerGoro** [comment] 2019-10-09 11:22
It seems we are mixing two different issues here:

I posted a GV patch for the fullscreen fallback issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1587366) when a session is restored. In a-frame they fallback to fullscreen when there are not VRDisplays. This case may be similar to #1777.

If you see the spinner then it's a different issue because the VRDisplay is found. @larsbergstrom

**Comment by larsbergstrom** [comment] 2019-10-09 12:32
@MortimerGoro No spinner ever appears in this case.

**Comment by bluemarvin** [comment] 2019-10-09 16:48
To be clear, how you can tell the two issues apart, if it is the restore bug, reloading the page will fix it. If it is the immersive mode failure, reloading the page will not fix it. The immersive mode failure is much harder to reproduce.

**Comment by MortimerGoro** [comment] 2019-10-28 19:26
I found another race condition which can cause the fullscreen issue. Bugzilla patch here: https://bugzilla.mozilla.org/show_bug.cgi?id=1591949

**Comment by bluemarvin** [comment] 2019-11-04 23:56
I believe this was fixed by https://github.com/MozillaReality/FirefoxReality/pull/2135

**Closed by bluemarvin** 2019-11-04 23:56 UTC
