### ISSUE TITLE
"Fullscreen is unavailable" message on Youtube.

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#836] opened 2018-11-26 19:58 UTC
## Hardware
Go 
a9da13e

## Steps to Reproduce
1. Watch video on Youtube.
2. Enter fullscreen

## Current Behavior
Youtube displays a "Fullscreen is unavailable" message.
Once out of fullscreen back to the standard YouTube video page, the Fullscreen icon greys out, but continues to function.

The problem is, that with this issue, the YouTube media controls UI doesn't disappear until you interact with it and dismiss the message, which is quite annoying.

![fullscreen](https://user-images.githubusercontent.com/1560884/49038717-9305d980-f172-11e8-8cb7-c5135c50f13c.png)

**Comment by philip-lamb** [comment] 2019-04-04 06:49
Closing as forward-duplicate of #1056.

**Closed by philip-lamb** 2019-04-04 06:49 UTC
Labels: P3, compatibility
