### ISSUE TITLE
[Pico] The Refresh and Stop Loading tooltips are not displayed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2835] opened 2020-02-21 15:34 UTC
**[Affected Versions]:**
- Firefox Reality 9 RC 2 (37ac4cbd)

**[Affected Platforms]:**
- Pico Neo 2 - Android - 8.1.0

**[Prerequisites]:**
- The headset is turned on.

**[Steps to reproduce]:**										
1. Open the app.
2. Hover over the Refresh button.
3. Observe if the "Refresh" tooltip is displayed.

**[Expected results]:**
- The tooltip is displayed.

**[Actual results]:**
- The tooltip is not displayed.

**[Notes]:**
- This issue is also reproducible with the Stop Loading tooltip.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=15DgYOLioLDKo62s7DuytLUhULOO0uc5A).

**Comment by keianhzo** [comment] 2020-02-24 10:21
@Softvision-RemusDranca I can't reproduce this with the latest master, I think it has been fixed by 889049d862764c9bad3354457fe0c05f9fccbe0e Could you please test again?

**Comment by Softvision-RemusDranca** [comment] 2020-02-24 14:14
@keianhzo It seems to be fixed for the Pico devices, but unfortunately now is reproducible on the other ones. 
I've tested on Oculus Go using the latest build from master and it's reproducible.
And on the other devices I've tested using the RC3 from v9 and it's reproducible.

**Closed** 2020-02-25 21:29 UTC
Labels: [QA]:Normal issue, in progress

**Comment by Softvision-GeluHaiduc** [comment] 2020-02-27 13:59
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 9 RC4 (c64365e3) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Pico Neo2 headsets.
Now, the “Refresh” and “Stop Loading” tooltips are displayed.
