### ISSUE TITLE
`<option selected>` in `<select multiple>` do not visually appear to be selected (in blue)

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#1013] opened 2019-03-14 22:11 UTC
## Hardware
Oculus Go, Pico G2

## Steps to Reproduce

1. Load https://webxr.sh/dropdowns#multiple.
2. Press the `<select multiple>` field to expose the choice list.
3. Select multiple `<option>`s, and press `OK` to update the value.
4. Notice there is a focus-ring outline on the first `<option>`, but none of the `<option selected>` values are properly highlighted in blue.
5. Notice if you press the `<select multiple>` field again, you can see that the previously selected options are stored. (And, by checking `<select multiple>.selectedOptions` you can see that the correct options are selected.)

## Current Behavior
In FxR, in a rendered `<select multiple>` on the page, when any values (e.g., the first two values) are selected, the rows are not properly highlighted as they are in Firefox for desktop:

![image](https://user-images.githubusercontent.com/203725/54270621-0c1c1780-453d-11e9-9681-89a2c6db66c1.png)

Notice that in FxR only the first row is ever "highlighted" (with the faint-blue focus ring):

![image](https://user-images.githubusercontent.com/203725/54269883-7338cc80-453b-11e9-88d0-1f3c8b869a38.png)

Compare with Oculus Browser:

1. Load `<select multiple>` test on https://webxr.sh/dropdowns#multiple.
2. Notice the default text will read **`Cherry`** (but if you modify the value and then reload the page, it will continue to read **`2 Selected`**).
    
    ![image](https://user-images.githubusercontent.com/203725/54269771-38cf2f80-453b-11e9-9ee1-89fceee85b63.png)
    ![image](https://user-images.githubusercontent.com/203725/54269825-4d132c80-453b-11e9-8adb-40bc802f5443.png)
    
<hr>

1. In Oculus Browser, Firefox Reality, and Firefox for desktop, scroll to https://webxr.sh/dropdowns#multiple.
2. Press the `<select multiple>` field, and press the rows such that four items are selected.
3. Press the checkmark icon to submit the changes.
4. Notice the text changes from `-- Please choose one or more --` to `4 Selected`.

In Oculus Browser:

![image](https://user-images.githubusercontent.com/203725/54270740-57cec100-453d-11e9-9c7d-8c81b7753369.png)

in FxR:

![image](https://user-images.githubusercontent.com/203725/54270946-bc8a1b80-453d-11e9-8fbd-d49e7ba46e65.png)

vs. in Firefox for desktop:

![image](https://user-images.githubusercontent.com/203725/54270621-0c1c1780-453d-11e9-9681-89a2c6db66c1.png)

## Expected Behavior

The selected options are highlighted in blue, à la Firefox for desktop:

![image](https://user-images.githubusercontent.com/203725/54270621-0c1c1780-453d-11e9-9681-89a2c6db66c1.png)

## Context
Originally discovered and reported in PR #1001: https://github.com/MozillaReality/FirefoxReality/pull/1001#pullrequestreview-213860959

**Comment by philip-lamb** [comment] 2019-05-08 04:45
Can't reproduce this as of current master. 
![org mozilla vrbrowser-20190508-164333](https://user-images.githubusercontent.com/5752887/57350042-a0f36800-71b0-11e9-90ae-214b523bbab2.jpg)

**Comment by philip-lamb** [comment] 2019-05-08 04:46
/remind me in one week Close this unless new regression / STR found.

**Closed** 2019-05-15 09:51 UTC
Labels: P3, bug, compatibility
