### ISSUE TITLE
There is no vertical scrollbar displayed for the "Bookmarks" page

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1694] opened 2019-08-28 14:09 UTC
**[Affected Versions]:**
- Firefox Reality 1.4-32400715 (08.28.2019)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32400715 (08.28.2019) apk. installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Navigate and bookmark ~ 10 websites using the "star" button from the URL search bar.
2. Click the "Bookmarks" button from the menu tray.
2. Observe the right side of the "Bookmarks" page.

**[Expected results]:**
- A vertical scrollbar is displayed.

**[Actual results]:**
- No scrollbar is displayed.

**[Notes]:**
- Attached is a screen shot of the issue:
![BookmarksScrollbar](https://user-images.githubusercontent.com/40061643/63862977-272cf780-c9b6-11e9-9763-5e48440a39da.png)

**Comment by keianhzo** [comment] 2019-09-23 14:31
@Softvision-RemusDranca I can't seem to reproduce this anymore, can you please confirm?

**Comment by Softvision-GeluHaiduc** [comment] 2019-09-24 12:04
@keianhzo I have tried to reproduce this issue with the latest Firefox Reality 1.5-32661642 (74326741) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets with no luck.
It seems that the issue is no longer reproducible.

**Comment by Softvision-GeluHaiduc** [comment] 2019-09-24 13:23
I'll mark this as wontfix, because the issue is still reproducible on version 1.4-32400715 of Firefox Reality.

**Closed** 2019-09-24 13:24 UTC
Labels: [QA]:Normal issue, [QA]:Wontfix issue
