### ISSUE TITLE
The entire text from an input/search field is wrongly deleted when long clicking the "Backspace" button

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2249] opened 2019-11-13 15:51 UTC
**[Notes]:**
- The entire text from an input field is deleted regardless of the content size, format and the text caret position.

**[Affected Versions]:**
- Firefox Reality version 6 RC5 (33a031c7)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened and the Settings menu is displayed.

**[Steps to reproduce]:**
1. Open a website in the browser.
2. Focus the Awesomebar and place the text caret at the middle of the URL.
3. Click and hold on the "Backspace" button from the keyboard displayed.
4. Observe the behavior.

**[Expected results]:**
- The text from the left side of the text caret is deleted.

**[Actual results]:**
- The entire text is deleted.

**[Additional Notes]:**
- This issue is also reproducible if the "Backspace" button is quickly clicked for ~ 4 times.
- This issue is also reproducible in the production version of the Firefox Reality app.
- This issue is not reproducible with the Oculus Quest default browser.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1QL1o3BVPCM1WW87rx-h-lLxXenGwYmAP)

**Comment by jvonitter** [comment] 2019-11-13 18:21
I agree that this is super gross but I don't think it will block FxR6 since it's pre-existing. Moving to 7

**Closed** 2019-11-20 22:02 UTC
Labels: [QA]:Major issue

**Comment by heres-maria** [comment] 2019-11-26 09:29
I have verified this issue and it is no longer reproducible with the Firefox Reality version 7 RC3 (7b66fb14) build. Only the text to the left of the caret is now deleted.
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
