### ISSUE TITLE
History feeds that are also bookmarked can not be deleted

### ISSUE THREAD

**Issue by heres-maria** [MozillaReality/FirefoxReality#2697] opened 2020-01-22 10:39 UTC
**[Affected Versions]:**
- Firefox Reality version 8 RC4 (f9c92a23)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- The feeds on the "History" page have also been bookmarked.

**[Steps to reproduce]:**                                        
1. Open “History”.
2. Delete a couple of (bookmarked) feeds using the trash can button.
3. Observe the behavior.

**[Expected results]:**
- All of the feeds you attempt to delete are removed.

**[Actual results]:**
- The bookmarked feeds you attempt to delete are not removed. 

**[Notes]:**
- Clearing the History either at sign out or from the “Clear History” option deletes the feeds.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1tP3wV_zBVjI0CoFniCivlv7G44wAkC2F/view?usp=sharing).

**Comment by keianhzo** [comment] 2020-01-22 14:53
@heres-maria This seems to be happening only when the deleted url is also bookmarked. This is what places is logging:

**Comment by heres-maria** [comment] 2020-01-22 15:14
I have updated the issue to reflect the info provided by @keianhzo.

**Comment by keianhzo** [comment] 2020-01-22 18:38
Also discovered that this is intermittent and only happens with some bookmarked URLs, I'm checking with the Sync to see what's going on.

**Comment by keianhzo** [comment] 2020-01-23 08:53
Related to this AS issue: https://github.com/mozilla/application-services/issues/2520

**Comment by keianhzo** [comment] 2020-02-17 11:31
Still blocked on the AS side. Pinged @linacambridge for triaging info.

**Comment by keianhzo** [comment] 2020-04-14 16:24
Still opened in AS

**Comment by keianhzo** [comment] 2020-04-20 09:23
@heres-maria I can't reproduce this any more in the current master, can you please verify?

**Comment by Softvision-GeluHaiduc** [comment] 2020-04-21 14:14
@keianhzo Unfortunately the issue is still reproducible for me using the latest Firefox Reality version 10-141111916 (d9a7eec5) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets. I tried both with a logged FxA account and without and the issue was still reproducible with different websites.

**Comment by keianhzo** [comment] 2020-04-21 14:48
@Softvision-GeluHaiduc Ok, I forgot that the STRs only work if the history entry ha been created after clicking on the bookmarked element, if you navigate to the page manually it doesn't happen.

This has been already fixed in AS/AC, it will be fixed when https://github.com/MozillaReality/FirefoxReality/pull/3096 is merged wich include an AC update.

**Comment by Softvision-GeluHaiduc** [comment] 2020-05-18 15:34
I have verified this issue with the latest Firefox Reality version 10 RC6 (140fb700) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Unfortunately, the issue is still reproducible.

Other steps to reproduce:
- Login into an FxA account and sync bookmarks and history.
- Select a bookmarked page and open it.
- Go to history and try to delete the feed of the bookmarked page.
The history feed that is also bookmarked is not deleted.

**Comment by Softvision-GeluHaiduc** [comment] 2020-05-18 16:00
I have verified the issue on the wrong build, I've retested it on the latest master, Firefox Reality version 11-141391233, installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets, and the issue is no longer reproducible. The history feed that is also bookmarked is deleted.

**Closed by Softvision-GeluHaiduc** 2020-05-18 16:00 UTC
Labels: AS, FxA, [QA]:Normal issue, in progress, regression
