### ISSUE TITLE
The Microphone permission prompt is no longer displayed after the Collect voice samples prompt is dismissed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#3101] opened 2020-04-03 12:12 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140931839 (a360c20).

**[Affected Platforms]:**
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.
- The Microphone permission is not granted.

**[Steps to reproduce]:**                                        
1. Click the Microphone button from the Awesomebar
2. Click the Allow or Don't Allow button from the Collect voice samples prompt.
3. Observe the behavior.

**[Expected results]:**
- The Collect voice samples prompt is dismissed and the Microphone permission prompt is displayed.

**[Actual results]:**
- The Collect voice samples prompt is dismissed but the Microphone permission prompt is NOT displayed.

**[Additional Notes]:**
- The Permission prompt is displayed after clicking again on the Microphone button.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1OEwI5ijJWSVaG_BeQ7P8vPE6UhmMiTXA).

**Comment by bluemarvin** [comment] 2020-04-06 18:41
I am not able to reproduce this issue on any of the devices (HTC, Pico, or Oculus).

**Comment by bluemarvin** [comment] 2020-04-06 18:57
I see it was fixed in #3108

**Closed by bluemarvin** 2020-04-06 18:57 UTC
Labels: [QA]:Normal issue, regression

**Comment by Softvision-RemusDranca** [comment] 2020-04-07 14:41
I have verified this issue and it's no longer reproducible with the latest Firefox Reality version 10-140941948 (633529f) build. Now, the Microphone permission prompt is displayed after the Collect voice samples prompt is Allowed/Not allowed.

Tested on Oculus Quest (Android 7.1.1),  HTC Vive Focus (Android 7.1.2) and Pico Neo 2 (Android 8.1.0).
