### ISSUE TITLE
Suggestions Bar Crash

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#745] opened 2018-11-10 18:25 UTC
I think it happened when clicking the URL bar clear button

```
2018-11-10 19:19:16.232 576-576/? E/cnss-daemon: Invalid mac address: 0x555555e110M
2018-11-10 19:19:35.023 2800-2800/org.mozilla.vrbrowser E/GeckoCrashHandler: >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 1 ("main")
    java.lang.IndexOutOfBoundsException: getChars (0 ... 69) ends beyond length 0
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1320)
        at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1202)
        at android.text.TextUtils.getChars(TextUtils.java:89)
        at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:67)
        at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1194)
        at mozilla.components.ui.autocomplete.InlineAutocompleteEditText.getOriginalText(InlineAutocompleteEditText.kt:124)
        at org.mozilla.vrbrowser.ui.views.NavigationURLBar.getOriginalText(NavigationURLBar.java:197)
        at org.mozilla.vrbrowser.ui.widgets.NavigationBarWidget.OnShowSearchPopup(NavigationBarWidget.java:782)
        at org.mozilla.vrbrowser.ui.views.NavigationURLBar$3.afterTextChanged(NavigationURLBar.java:342)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8203)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10382)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
        at android.text.SpannableStringBuilder.clear(SpannableStringBuilder.java:239)
        at org.mozilla.vrbrowser.ui.views.NavigationURLBar$2.onClick(NavigationURLBar.java:319)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22436)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6143)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
2018-11-10 19:19:36.080 1551-1667/? E/VrManagerNative: getProviderPropertyString not supported
```

**Comment by keianhzo** [comment] 2018-11-21 16:58
Dupe of #783

**Closed by keianhzo** 2018-11-21 16:58 UTC
Labels: P1, bug
