### ISSUE TITLE
GeckoSession.goBack() can be unresponsive during a heavy page load

### ISSUE THREAD

**Issue by nancyhang** [MozillaReality/FirefoxReality#682] opened 2018-10-27 01:22 UTC
Reported by @bluemarvin 

This issue seems to be exacerbated on devices running the Snapdragon 821 chip set such as the Oculus Go and Google Pixel 1. This issue was specifically called out by Oculus during the Oculus App Store review of Firefox Reality. The issue gives the appearance that GeckoView is unable to go back until a page load has completed. Many pages at https://sketchfab.com/ download a great deal of data and often display this behavior. New devices that use the Snapdragon 835 chip set such as the Pixel 2 do not seem to display this issue to such a degree and are much more responsive. However, the 835 is a much higher performance chip set.

https://bugzilla.mozilla.org/show_bug.cgi?id=1493225

**Comment by cvan** [comment] 2019-02-22 11:04
@rbarker: I'm having a difficult time understanding the dialogue in the GeckoView bug you reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1493225

I can reproduce this consistently on the Go, Pico, and Focus:

1. Load https://sketchfab.com/paul_sketch/collections/vr-homes in FxR.
2. Click a model's link.
3. Let the page fully load.
4. Go back in history.
5. When I let the [previous page](https://sketchfab.com/paul_sketch/collections/vr-homes) load, if I don't want for the page to fully complete the loading of all its requests (which is a lot + plus all the JS running), when I click on a _different_ model's link, the URL from the _previous_ model's link.

Is this the same issue as described here in and in [bug 1493225](https://bugzilla.mozilla.org/show_bug.cgi?id=1493225)? Or am I experiencing a different issue? If so, let me know, and I'll file separately - with video captures, screenshots, and logs. Thanks.

**Comment by bluemarvin** [comment] 2019-02-23 01:05
I think this might be the same issue. What I think might be happening is if you click a link while GeckoView is under a heavy JS load either things are missed or queued up wrong. It wouldn't hurt to file what you are seeing with video and comment in https://bugzilla.mozilla.org/show_bug.cgi?id=1493225 pointing them to your issue. At a minimum it will give them additional test cases to verify that the solution works. Additionally, it would be helpful if you could try to reproduce in either the GeckoView Example application or the new reference browser (often referred to as r-b).

**Comment by philip-lamb** [comment] 2019-03-09 03:06
Duplicate of #534. Will close that and forward references here.

**Comment by philip-lamb** [comment] 2019-05-20 20:49
Fixed in #1164

**Closed by philip-lamb** 2019-05-20 20:49 UTC
Labels: Bugzilla, in progress, perf
