### ISSUE TITLE
Controller placement needs to be adjusted

### ISSUE THREAD

**Issue by thenadj** [MozillaReality/FirefoxReality#221] opened 2018-07-20 16:53 UTC
Hardware: Oculus Go
REPRODUCE: Home
CURRENT BEHAVIOR: Controller feels placed too high in space
EXPECT: Controller to be in the same placement in VR as in real life
RECOMMENDATION: Move controller 10cm down and 10cm closer

**Comment by cvan** [comment] 2018-07-20 21:08
I think this is a dupe of issue #196. Feel free to close if you feel it is.

**Comment by thenadj** [comment] 2018-07-21 15:20
Those are different. 196 is about creating a new visual design for the way the laser beam and cursor look. 221 is about repositioning the controller in space.

**Comment by avrignaud** [comment] 2018-11-02 21:05
@thenadj Can you take a look and see if this is still an issue?

**Comment by thenadj** [comment] 2018-11-09 05:32
@avrignaud Nope, that has been fixed a long time ago. Closing issue.

**Closed** 2018-11-09 05:33 UTC
Labels: P1, enhancement
