### ISSUE TITLE
The app is automatically restarted and the crash dialog box is displayed after quitting from 360 videos

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1770] opened 2019-09-04 12:05 UTC
**[Notes]:**
- While reproducing this issue, it once blocked the Oculus Quest device. Here is a video recording with that behavior: [link](https://drive.google.com/open?id=1eKviDnnltwz-RXe2mfBqjxJvzqUufp8e)
- Also if this issue is reproduced while having multiple windows opened and the 360 video is opened from the right or left window, after the app is automatically restarted, the windows overlap. Here is a video recording with that behavior: [link](https://drive.google.com/open?id=13l0FQFFc-7YCA4HraAMFiqHbWRj4-zZf)

**[Affected Versions]:**
- Firefox Reality 1.4-32450938 (RC2)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Open a 360 video(I opened one recommended from Vimeo)
2. Click the "Play" button.
3. Click the "full screen" button from the video options.
4. Click the "Oculus" button from the controller.
5. Click the "Quit" button from the prompt displayed and observe the behavior.

**[Expected results]:**
- The app is closed and the "Homepage” of the device is displayed.

**[Actual results]:**
- The app is automatically restarted and the crash dialog box is displayed.

**[Additional Notes]:**
- This issue is also reproducible if quiting from 360 videos while in theater mode.
- This issue is also reproducible with 360 videos from Youtube.
- After the app  is automatically restarted and the crash dialog box is dismissed the window displayed has a different size from the initial settings applied and the buttons for the video are slightly smaller. 
- Attached is the video recording of the issue and the crash report received:
	- Video recording: [link](https://drive.google.com/open?id=1MUU_K3rkX5gWlI5Mwap9If6P0EBTIc1V)
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/bp-6045c440-60b4-4f97-a326-d335c0190904)

**Comment by Softvision-RemusDranca** [comment] 2019-09-04 12:18
In addition to the details provided above, it seems that there are some visual glitches displayed by the device after resuming the app, that "run" through the view.

**Comment by Softvision-GeluHaiduc** [comment] 2019-09-06 11:38
I have verified this issue with the latest Firefox Reality 1.4-32481747 RC3 installed on the Oculus Go, Quest and HTC Vive Focus Plus headsets and it is still reproducible.
- On the Oculus Go the issue is intermittently reproducible with 360 youtube videos, crash report [here](https://crash-stats.mozilla.com/report/index/bp-3deaeb5e-1be0-4abb-a133-ba2780190906), and is always reproducible on 360 vimeo videos, crash report [here](https://crash-stats.mozilla.com/report/index/bp-19c122c8-eb6c-4e69-8920-535cf0190906).
- On the Oculus Quest the issue is still reproducible with both youtube and vimeo videos.
- On the HTC Vive Focus Plus the issue is intermittently reproducible if multiple windows were opened after the app is resumed they overlap.

Considering this I will reopen this issue.

**Comment by bluemarvin** [comment] 2019-09-06 15:49
>     * On the HTC Vive Focus Plus the issue is intermittently reproducible if multiple windows were opened after the app is resumed they overlap.
> 

To be clear, you are not seeing a crash on HTC, but you do see a different issue when FxR is resumed where the windows overlap? If that is the case, I think that is a different issue and should be filed separately. Thanks.

**Comment by bluemarvin** [comment] 2019-09-06 18:10
I have not yet been able to reproduce the issue on my Go using the 64 bit build of rc3.

**Comment by MortimerGoro** [comment] 2019-09-06 18:14
I can't reproduce it either. I tried on both Go and Quest with Youtube and Vimeo videos

**Comment by jvonitter** [comment] 2019-09-06 18:23
I'm able to repro it pretty reliably on Quest with Youtube. Will try on the Go

**Comment by bluemarvin** [comment] 2019-09-06 19:06
A reboot fixed the issue for @jvonitter. This is starting to look like a bug in the oculus system where if a device is left on for too long, system resources are leaked and the system becomes unstable. I'm leaving my Quest plugin in and powered on and will try to reproduce the issue through the day to try and validate the cause.

**Comment by jvonitter** [comment] 2019-09-06 19:43
In case it's useful, here's a log that covers my activity between [one crash](https://crash-stats.mozilla.com/report/index/bp-e6c6389b-c8f9-4716-babb-c44e20190906) and [another]( https://crash-stats.mozilla.com/report/index/bp-c56c32e1-1e11-4977-a1d3-919140190906).

[logcat1113100906.txt](https://github.com/MozillaReality/FirefoxReality/files/3585483/logcat1113100906.txt)

**Comment by jvonitter** [comment] 2019-09-06 20:39
another, even better log: 
[1770repro.log](https://github.com/MozillaReality/FirefoxReality/files/3585655/1770repro.log)

**Comment by bluemarvin** [comment] 2019-09-07 00:31
This appears to have been caused by Android issue https://issuetracker.google.com/issues/37123764
The attempted fix is to ensure animations do not run when views get destroyed on exit and was implemented in https://github.com/MozillaReality/FirefoxReality/pull/1786.

**Comment by Softvision-RemusDranca** [comment] 2019-09-09 12:54
I have retested this issue on HTC Vive Focus Plus, at it seems that a different issue occurs that is also reproducible on all devices. Considering this, I logged a new issue #1798 and I will remove the HTC Vive Focus Plus device from this issue.
The crash I encountered on the HTC device could have been related to Youtube videos. I will continue to investigate on that. 
@bluemarvin Thanks for pointing out this behavior!

**Comment by bluemarvin** [comment] 2019-09-09 19:30
Since we can't seem to prevent triggering the crash on exit, I'm just going to prevent the crash reporter from restarting FxR from a crash after `onDestroy()` is called.

**Comment by bluemarvin** [comment] 2019-09-09 23:18
Fixed by https://github.com/MozillaReality/FirefoxReality/pull/1801

**Closed by bluemarvin** 2019-09-09 23:18 UTC
Labels: [QA]:Blocker issue

**Comment by Softvision-RemusDranca** [comment] 2019-09-10 12:38
I have verified this issue and it's no longer reproducible with the latest Firefox Reality 1.4-32522317 (RC5) installed. Verified with multiple 360 videos from Vimeo and Youtube.
Tested on the Oculus Go and the Oculus Quest headsets.
