### ISSUE TITLE
Permissions granted to a website are not being holded while in the same session

### ISSUE THREAD

**Issue by andrenatal** [MozillaReality/FirefoxReality#460] opened 2018-09-01 01:03 UTC
## Hardware
Oculus Go
## Steps to Reproduce
1. Go to http://amctheatres.com/
2. Go to `Showtimes`
3. Accept the website's ask for location permissions
4. Go to `Showtimes` again
5. The permission is asked again

## Current Behavior
The permissions keep being asked on and on, instead holding it throughout the whole session.

## Expected Behavior
After we grant the website permission once, we shouldn't ask it again if the user didn't leave the website.

## Possible Solution
Store all the permissions given to that specific website throughout the whole session.

## Context
It's very annoying to see the permission prompt on every page on the same website on and on

```
```

</details>

**Comment by bluemarvin** [comment] 2018-09-01 01:06
This a dupe of https://github.com/MozillaReality/FirefoxReality/issues/264

**Closed** 2018-09-04 17:07 UTC
Labels: duplicate
