### ISSUE TITLE
The app crashes after reopening FxR with the device language changed

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2670] opened 2020-01-17 14:11 UTC
**[Affected Versions]:**
- Firefox Reality version 7.1-40080314 (dd5419a2)
- Firefox Reality version 8 RC1 (7a444d0c)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- Change the device language to another one.

**[Steps to reproduce]:**
1. Open the Firefox Reality browser.
2. Press the Oculus/Vive button on the controller and quit the app.
3. Change the device language to a different one. (if asked restart the device)
4. Open the Firefox Reality browser and observe the behaviour.

**[Expected results]:**
- The browser opens correctly.

**[Actual results]:**
- The browser crashes when opened.

**[Notes]:**
- The issue is also reproducible in production.
- The issue is reproducible with almost all the device languages.
- Sometimes the app doesn't open on first try on the HTC devices.
- With some languages the app doesn't open at all on the Oculus devices.
- Attached a screen recording of the issue on the HTC device [here](https://drive.google.com/open?id=1GG2ilIjM6rL7HKTMHgBeE_FeQFYXzgKe).
- Attached a screen recording of the issue on the Oculus device [here](https://drive.google.com/open?id=1mVN6NhZtvobx7DjQ2ogUuRk1FICql9I3).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1dOXxm-wWweAGwJ9H8jimyqIQVcya1Kvq).
- The crash report can be found [here](https://crash-stats.mozilla.com/report/index/888d4969-3849-4645-aaa2-c89450200117).

**Comment by Softvision-RemusDranca** [comment] 2020-01-20 11:59
I have verified this issue and it's no longer reproducible on the Oculus devices with the latest Firefox Realty 8 RC2 (4ff1f59). 
However, this issue is still reproducible on the HTC devices.

Considering this, I will reopen this issue.

**Comment by keianhzo** [comment] 2020-01-23 08:57
Duplicate of #2693

**Closed by keianhzo** 2020-01-23 08:57 UTC
Labels: [QA]:Major issue, in progress

**Comment by Softvision-GeluHaiduc** [comment] 2020-01-27 09:06
As the HTC side of the issue will be addressed in #2693 I will label this as wontfix.
