### ISSUE TITLE
No access to downloaded files on Oculus Quest

### ISSUE THREAD

**Issue by assadollahi** [MozillaReality/FirefoxReality#1422] opened 2019-07-18 06:43 UTC
## Hardware

Oculus Quest

## Steps to Reproduce

Go to website, for example tinkercad.com, design some file, click download as .obj file.

## Current Behavior

the downloaded file is not accessible. in contrast, Oculus Browser allows users to acess downloaded files.

## Expected Behavior

the file should be accessible. i actually don't even know whether the browser is allowed to write into the corresponding directory.

## Possible Solution

change the apk rights for android, write in default downloads directory.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by philip-lamb** [comment] 2019-07-18 10:12
Thanks for the report. We've got the same thing logged already and on our roadmap. Duplicate of #672

**Closed by philip-lamb** 2019-07-18 10:12 UTC
