### ISSUE TITLE
The hover effect and the trash and 3 dot menu do not appear when the downloaded item is hovered by the pointer except when hovered on the far right side

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3155] opened 2020-04-14 12:39 UTC
**[Affected Versions]:**
- Firefox Reality version 10-141042250 (207f86b5)

**[Affected Platforms]:**
- Pico G2 4K - Android 8.1.0
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.
- Make sure to have a downloaded file in the Downloads View.

**[Steps to reproduce]:**
1. Click the Downloads button from the menu tray.
2. Using the controller hover the downloaded item.
3. Observe the behaviour.

**[Expected results]:**
- The downloaded item gains a hover effect and the trash and 3dot menu appear on the far right side.

**[Actual results]:**
- The downloaded item does not gain a hover effect and the trash and 3dot menu do not appear on the far right side.

**[Notes]:**
- The issue is also reproducible with the bookmarks and history feeds.
- The issue is not reproducible if the item is hovered on the far right side where the date and time are.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1hfO0w5r7p2Y6GpRrE4lvDbwoFfTLS_8E/view?usp=sharing).

**Comment by bluemarvin** [comment] 2020-04-15 23:42
I'm not able to reproduce this issue. I tried on both Neo2 and G2 4K. I even tried downloading a file with a short file name to see if that had any effect. Bookmarks and History also both worked as expected.

**Comment by Softvision-GeluHaiduc** [comment] 2020-04-16 09:18
The issue is still present for me. I used Firefox Reality version 10-141060720 (fa882ff2) installed on the Pico Neo2 and Pico G2 4K. [Here](https://drive.google.com/file/d/15lVxySN9Fah9rxMgUUpoGLhURMfnDIy6/view?usp=sharing) is a video of the behavior.
If I hover the feed in the middle the trash and 3dot menu do not appear and when I hover the far right side the buttons appear. On the oculus and htc headsets if you hover the feed anywhere the trash and 3dot menu appears.

**Comment by keianhzo** [comment] 2020-04-16 10:16
This was related to HW acceleration not being enabled by default due to a regression. That should be fixed in master and now it should work properly with the default settings. 

This PR also fixes it for Pico devices when HW acceleration is disabled: https://github.com/MozillaReality/FirefoxReality/pull/3172

**Closed** 2020-04-16 16:42 UTC
Labels: [QA]:Major issue, in progress

**Comment by Softvision-GeluHaiduc** [comment] 2020-04-21 10:05
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-141111916 (d9a7eec5) installed on the Pico Neo2 and Pico G2 4K headsets.
Now, the hover effect and the trash and 3 dot menu appear when the downloaded/bookmark/history item is hovered anywhere by the pointer.
