### ISSUE TITLE
The app has bad performance issues and it's functionalities don't work properly after clearing cookies/site data or the cached web content

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2124] opened 2019-11-01 16:50 UTC
**[Affected Versions]:**
- Firefox Reality version 6 RC1 (a83b2bf9)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Go to Settings and open the Privacy & Security card.
2. Click the "Clear Data" button for the "Cookies and Site Data" or the "Cached Web Content" option
3. Dismiss the menu and navigate to a website or check other functionalities (ex: Resize, Bookmark, Tray). 
4. Observe the behavior.

**[Expected results]:**
- The website is rendered correctly and all functionalities work as expected.

**[Actual results]:**
- The website is hardly loading, major functionalities are not working properly and the UI is affected.

**[Notes]:**
- Only the opened windows are affected by this issue.
- I also encountered this behavior when the Tracking Protection option is enabled or disabled. This issue is documented in bug: #2121.
- Attached are a screen recording of the issue along with the logcat file: 
      - Screen Recording: [link](https://drive.google.com/open?id=1RxQa3CSDYFk2X7SVKfqJtG9Ui3BPL9Lm)
      - Logcat: [link](https://drive.google.com/open?id=1O1rrVh8g-liZoc-oErAMRYNylOO4VBGl)

**Comment by bluemarvin** [comment] 2019-11-01 17:09
I think this is a dupe of #2121 I will verify.

**Comment by bluemarvin** [comment] 2019-11-01 17:17
I have verified that the issue fixed by #2125 is the same issue.

**Closed by bluemarvin** 2019-11-01 17:17 UTC
Labels: [QA]:Major issue

**Comment by Softvision-RemusDranca** [comment] 2019-11-04 14:40
I have verified this issue and it's no longer reproducible with the Firefox Reality 6-33052017 (67257542) build.
Tested on the Oculus Quest (Android 7.1.1), Oculus Go (Android 7.1.2), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2) devices.
