### ISSUE TITLE
Keyboard appears upon a crash

### ISSUE THREAD

**Issue by cvan** [MozillaReality/FirefoxReality#849] opened 2018-11-27 05:43 UTC
## Hardware

Oculus Go
f5e522d

## Steps to Reproduce

1. Load the URL `about:crashparent`
2. Notice upon relaunch, the keyboard appears opened

## Context
Related: issue #846

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by keianhzo** [comment] 2018-12-13 22:43
Probably related or duplicate of #846

**Comment by keianhzo** [comment] 2018-12-18 14:54
Fixed with #889 Closing.

**Closed by keianhzo** 2018-12-18 14:54 UTC
Labels: backlog, in progress
