### ISSUE TITLE
[Pico]WebXR scene display is not clear

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3293] opened 2020-04-30 11:17 UTC
## Configuration

Firefox Reality version: Firefox Reality version 10-141060720
Firefox Reality build ID: 9b36c14

Hardware: 

## Steps to Reproduce

1. Open link "https://mixedreality.mozilla.org/hello-webxr/"
2. Click goggle icon to start WebVR experience
3. 

## Current Behavior

WebVR scene is not as clear as v9-rc10 version

## Context

Please confirm if it's due to the reason that MSAA can't be enabled dynamically in Pico SDK

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment] 2020-04-30 23:02
This is unfortunately caused by WebXR not supporting MSAA at this time. In v9 the page used WebVR which did support MSAA but in v10 it is using WebXR which has not yet stabilized automatic framebuffer antialiasing in the spec. We are working to get the WebXR standard updated to support MSAA and hopefully we can have this issue resolved by v11.

**Comment by bluemarvin** [comment] 2020-04-30 23:58
We have made some adjustments in v10 rc4 that should help improve image quality until MSAA can be enabled for WebXR immersive experiences.

**Closed** 2024-07-22 11:47 UTC
Labels: WebVR/XR, ARCHIVED
