### ISSUE TITLE
Use the same cylinder geometry for all borders/widgets

### ISSUE THREAD

**Issue by MortimerGoro** [MozillaReality/FirefoxReality#1646] opened 2019-08-23 17:04 UTC
Requires: https://github.com/MozillaReality/vrb/issues/73

I want to reuse a single cylinder geometry for all widgets (on non layers devices) and for all resize/hover borders with layer devices. This will avoid some small delays while creating new cylindrical widgets or borders (e.g. resize, hover)

**Comment by bluemarvin** [comment] 2019-10-15 18:40
I'm hoping fixing this issue will also fix the jank that happens when creating a new window.

**Comment by bluemarvin** [comment] 2020-02-12 01:46
This may not actually be feasible. Additionally, the jank was primarily caused by shader compilation which should be fixed by #2773

**Closed** 2024-07-22 11:48 UTC
Labels: in progress, ARCHIVED
