### ISSUE TITLE
Cannot type into address bar on Daydream

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/FirefoxReality#1526] opened 2019-08-06 22:21 UTC
## Hardware
Daydream View (2017) with a Galaxy S8

## Steps to Reproduce

1. Type a few characters into the address bar
2. Try deleting characters with the backspace button

## Current Behavior

Each character you type replaces the previous character. The backspace key does not delete the character either. See the following video:
https://gfycat.com/kindsinfulkid

## Expected Behavior

You should be able to use the address bar.

<details open>

```
```

</details>

**Comment by philip-lamb** [comment] 2019-08-06 22:33
Thanks for the report... there were anecdotal reports of this in the Play Store comments, so its helpful to know the config. Can you add the version and build number (accessible by clicking on the version number in settings)

**Comment by brianpeiris** [comment] 2019-08-06 22:46
Version 1.3, 2019-07-17, Build 9000adc

**Comment by bluemarvin** [comment] 2019-08-06 23:08
In my experience the Daydream support on Samsung has never really worked well. I've tested on both Mirage and Pixel 2 and could not reproduce the issue. I also tested it on my S8 and could not reproduce the issue. Did you encounter this on launch or had you been using the app for a while?

**Comment by brianpeiris** [comment] 2019-08-06 23:11
I can repro immediately on launch.

**Comment by bluemarvin** [comment] 2019-08-06 23:12
Is it 100% or intermittent? I'm still playing around with my s8 and have still not been able to reproduce the issue.

**Comment by brianpeiris** [comment] 2019-08-06 23:12
It's 100% for me, so far.

**Comment by bluemarvin** [comment] 2019-08-06 23:34
Have you tried a clean install? `adb uninstall org.mozilla.vrbrowser` I'm not really sure what else to try at this point with out a way to reproduce it locally.

**Comment by brianpeiris** [comment] 2019-08-07 01:42
Clean install doesn't help. It still reproduces consistently on launch. 
Here's another data point, this only affects alphanumeric keys, not symbol keys!

**Comment by bluemarvin** [comment] 2019-08-07 01:50
What version of android is your S8 running?

**Comment by brianpeiris** [comment] 2019-08-07 16:46
Android 9

**Comment by bluemarvin** [comment] 2019-08-07 16:57
Okay, I'm on Android 8 so my guess at this point is that something in Android 9 broke our keyboard. I think something similar happened when Android 8 was released. I'm hesitant to upgrade my phone to test.

**Comment by bluemarvin** [comment] 2019-08-07 17:43
FxR works as expected on a Pixel 1 running Android 9. So it is starting to look more like a Samsung issue, I guess I will upgrade my S8 to Android 9 to see if it reproduces.

**Comment by bluemarvin** [comment] 2019-08-07 18:20
Upgrading my S8 to Android 9 and FxR keyboard sill works for me. Running out of ideas of what to try.

**Comment by bluemarvin** [comment] 2019-08-23 23:20
I haven't forgot about this, I just haven't had time to figure out why my S8 won't upgrade to android 9.

**Comment by bluemarvin** [comment] 2020-06-02 20:25
Closing since we no longer support GoogleVR.

**Closed by bluemarvin** 2020-06-02 20:25 UTC
Labels: P3, bug, platform:Daydream
