### ISSUE TITLE
Clicking "Accept the risk and continue" doesn't reposnse when applying KRpano local network SSL cert test

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3540] opened 2020-06-24 10:46 UTC
## Configuration

Firefox Reality version: Firefox Reality 10-RC7
Firefox Reality build ID: bda5ecf

Hardware: 
Pico Neo2 - Android 8.1
Pico G2 4K - Android 8.1
Oculus Quest

## Steps to Reproduce

1. Install Krpano with krpano testing server (GUI version). 
2. Referring to krpano doc here: [https://krpano.com/docu/tools/testingserver/#https](url) and create SSL certificates. Then make sure the local PC IP address is accessible with `https:` prefix
3. Open Firefox Reality and input the address displayed from [krpano testing server](https://krpano.com/docu/tools/testingserver/#gui)
4. See the security warning page and click "Advanced..."
5. In expanded menu click "Accept the risk and continue" then observe.

## Current Behavior

Webpage doesn't respond to clicking "Accept the risk and continue" button. 

## Expected Behavior

When clicking "Accept the risk and continue", can view the file system from the directory specified by the IP address.

## Context

It's applicable to use mobile browsers for this testing case.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by bluemarvin** [comment] 2020-07-28 20:17
I am not able to reproduce this issue locally using FxR 12 and krpano 1.20.7 test server:
![Screenshot_org mozilla vrbrowser internal_2020 07 28-16 15 04](https://user-images.githubusercontent.com/3066/88716817-7e5eaf00-d0d4-11ea-911a-d934ef25358a.jpeg)

**Comment by bluemarvin** [comment] 2020-07-28 20:21
I'm closing this since it worked fine for me in both latest release (11.2) and latest development build (12). Please re-open if there are additional step to consider when reproducing.

**Closed by bluemarvin** 2020-07-28 20:21 UTC
