### ISSUE TITLE
The pages are reloaded and the performance is affected when enabling/disabling PB while multiple windows are opened 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2443] opened 2019-12-09 15:01 UTC
**[Notes]:**
- In some instances the windows froze if PB mode was disabled/enabled multiple times.

**[Affected Versions]:**
- Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Click "+" button twice to open 2 new windows.
2. Click the Private Browsing button from the tray.
3. Click "+" button twice to open 2 new PB windows.
4. Click again the Private Browsing button to exit PB.
5. Observe the behavior.

**[Expected results]:**
- The windows are correctly rendered.

**[Actual results]:**
- The windows are reloaded and performance issues occur.

**[Additional Notes]:**
- This issue is also reproducible if a new tab is created while having multiple windows opened (2 windows).
- This issue is always reproducible if 3 windows are opened in each browsing mode and PB is enabled/disabled.
- The pages are not reloaded if only one window is opened in each browsing mode and PB is enabled/disabled.
- Attached is the screen recording and the logcat of the issue:
	- Screen Recording: [link](https://drive.google.com/open?id=1AhSjju8g2X9ArtygK_NEFRGXVu-O2Xby).
	- Logcat: [link](https://drive.google.com/open?id=17rvFvbB3XJ45-dkrOo-GgFgcCVXw1H-k).

**Comment by bluemarvin** [comment] 2019-12-09 21:30
This looks like expected behavior to me. We have a limit of 5 active sessions for memory reasons. If you have three windows open in both private and regular browsing, any time you switch between the two, the inactive windows get killed. So when switching back it may take some time to recreate the sessions.

**Comment by jvonitter** [comment] 2019-12-09 21:40
i'll take a look at our multiwindow data and see how common it is for people to have this many windows open at once.

**Comment by Softvision-RemusDranca** [comment] 2019-12-10 10:36
I wasn't aware that this is expected since this behavior is not reproducible in the production version of the app (v5).
I've noticed this behavior, when creating new tabs and then enabling/disabling PB mode. From my understating this is expected and this was the main reason for this functionality (please correct me if I'm wrong).

As a side effect of this issue if videos are opened in multiwindows the "Play" button wrongly changes to "Pause" even if the video is in the pause state, resulting in the button being unactionable. Here is a [screen recording](https://drive.google.com/open?id=18S0MGtDQ1lLAikiWfCl5GrQHJSojsnCn) for this behavior.
Should I log a new issue for this side effect, since the reload behavior is expected?

**Comment by jvonitter** [comment] 2019-12-10 17:44
@Softvision-RemusDranca We added the max sessions along with tabs, which is why you dont see this in FxR5. Since each window has minimum one tab in it, having 6 windows open has one more tab than the current limit. We can change the limit, but I wanted to check usage to see how many windows folks typically use first.

and yes, i think logging a separate issue for the play/pause button is a good idea.

**Comment by Softvision-GeluHaiduc** [comment] 2020-01-16 15:34
During testing of the V8 RC build I encountered this issue witch also lead to a crash on the device (HTC Vive Focus Plus) [here](https://drive.google.com/open?id=15BwEqQFehTLUeTVk2tWmYgJbyWS-qaCy) you can find the logcat file and [here](https://crash-stats.mozilla.com/report/index/fb6a80b2-d7f2-40bb-bdcb-88dd20200116) is the crash report.

**Comment by bluemarvin** [comment] 2020-01-16 16:41
> During testing of the V8 RC build I encountered this issue witch also lead to a crash on the device (HTC Vive Focus Plus) [here](https://drive.google.com/open?id=15BwEqQFehTLUeTVk2tWmYgJbyWS-qaCy) you can find the logcat file and [here](https://crash-stats.mozilla.com/report/index/fb6a80b2-d7f2-40bb-bdcb-88dd20200116) is the crash report.

That crash is from an OOM, so not related.

**Comment by Softvision-GeluHaiduc** [comment] 2020-01-16 16:47
@bluemarvin Should we log this in a separate issue?

**Comment by bluemarvin** [comment] 2020-01-16 17:20
Unfortunately OOMs happen and the stack trace doesn't contain any actionable information. I'm not sure what we can do about it unless it is a frequent issue and I only see the single crash you reported on crash stats.

**Comment by keianhzo** [comment] 2020-05-01 13:46
@bluemarvin do we still need this issue open? This seems to be the expected behaviour.

**Comment by bluemarvin** [comment] 2020-05-01 17:38
Yep, I'll close as won't fix.

**Closed by bluemarvin** 2020-05-01 17:38 UTC
Labels: [QA]:Major issue, wontfix
