### ISSUE TITLE
FxR crashes after a configuration change

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#2693] opened 2020-01-21 16:11 UTC
## Configuration

Firefox Reality version: 4ff1f5916302cb439d6d7bfff7573e14497545da
Firefox Reality build ID: eb9a1ec3e1d5ebfb37bb2686b134092b589d35a1

Hardware: 
HTC Vive Focus Plus - Android 7.1.2
HTC Vive Focus - Android 7.1.2
PicoVR (All)

## Steps to Reproduce

1. Open FxR
2. Exit to the dashboard
3. Go to the system settings and change the language
4. Open FxR

## Current Behavior

The app crashes after being relaunched.

## Expected Behavior

The app should open successfully.

## Context

During a normal Dashboard and app reopen flow, the lifecycle flow looks like:
`onPause` -> `onStop` -> (**DashBoard**) -> `onStart` -> `onResume`

But after a configuration change the flow is:
`onPause` -> `onStop` -> (**Configuration Change**) -> `onDestroy` -> `onCreate` -> **CRASH**

## Error Logs and Stack Traces

<details open>

```
java.lang.IllegalArgumentException
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1020)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1330)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
	at org.mozilla.vrbrowser.VRBrowserActivity.onDestroy(VRBrowserActivity.java:5)
	at android.app.Activity.performDestroy(Activity.java:7090)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1171)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4533)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4571)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1588)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6608)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:972)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)
```

</details>

**Comment by Softvision-RemusDranca** [comment] 2020-01-21 16:36
@keianhzo, Isn't this an duplicate of #2670?

**Comment by keianhzo** [comment] 2020-01-21 17:47
@Softvision-RemusDranca the root cause it's different, this is a life cycle related issue and it's been there probably since v1. I'd leave this one and close #2670

**Comment by philip-lamb** [comment] 2020-01-24 01:25
Reportedly, on iQiyi devices the app can't be reopened after this crash. Log at https://drive.google.com/open?id=15CViLlH8l9RJ3mzO5KoYy4_AyEWhuMWc

**Comment by keianhzo** [comment] 2020-01-28 16:12
@philip-lamb It is not related to this one but it should be fixed for v8. Do we know what version are they running in this Log?

**Comment by philip-lamb** [comment] 2020-01-28 21:53
I'll check (if its not in the log) but it is most likely FxR 6 GM release.

**Closed** 2020-01-31 18:35 UTC
Labels: crash 🔥, in progress
