### ISSUE TITLE
Suggestion widget crash

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#783] opened 2018-11-20 02:04 UTC
## Hardware

Go

## Steps to Reproduce

1. Type some text into the URL bar.
2. Click on browser window.
3. Press home button (notice back button no longer works).
4. Launch FxR again.
5. Try to type in the URL bar.

## Current Behavior

Crash:
https://crash-stats.mozilla.com/report/index/a326acaa-7713-4e2c-a587-c84b20181120
## Expected Behavior

Should be able to type and get suggestions.

**Comment by cvan** [comment] 2018-11-20 04:49
It appears this is a dupe of #745, yeah? If so, feel free to close this and paste the URL to the Socorro report. Thank you!

**Comment by bluemarvin** [comment] 2018-11-20 04:52
It could be a dupe, but I gave STR which #745 doesn't seem to have?

**Comment by cvan** [comment] 2018-11-20 05:10
You can forward-dupe #745 and close that. That seems fine. Thanks!

**Closed** 2018-11-22 21:15 UTC
Labels: bug, in progress
