### ISSUE TITLE
[Intermittent] The window is navigated back after multiple websites are having ETP disabled

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#3132] opened 2020-04-08 12:17 UTC
**[Affected Versions]:**
- Firefox Reality version 10-140982354 (bce60f9d)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate on multiple websites and disable ETP from the shield icon.
2. After the refresh observe the loaded webpage

**[Expected results]:**
- The website on which ETP was disabled is loaded.

**[Actual results]:**
- The previously visited webpage is loaded.

**[Notes]:**
- The window can not be navigated forward.
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1veU2-DBU_8SACEFFf1L-cR6OMMe9n7_q/view?usp=sharing).

**Comment by bluemarvin** [comment] 2020-04-13 21:29
I think this will be fixed once https://bugzilla.mozilla.org/show_bug.cgi?id=1625585 is fixed. I believe the problem is we are recreating the session and sometimes we have not updated the restore information when the window gets recreated. Once the GV issue is fixed we should be able to just reload the session instead of recreate it.

**Closed** 2020-04-22 19:22 UTC
Labels: [QA]:Normal issue, blocked, regression

**Comment by Softvision-GeluHaiduc** [comment] 2020-04-23 10:07
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10 RC1 (6db2f60a) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets.
Now, the window is not navigated back after disabling ETP on multiple websites in a row.
