### ISSUE TITLE
The app crashes after opening a 3rd window if the first one has a "3x" size

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#1619] opened 2019-08-21 13:54 UTC
**[Affected Versions]:**
- Firefox Reality 1.4-32322148 (08.20.2019)

**[Affected Platforms]:**
- Oculus Pacific - Android 7.1.2 (Oculus Go)
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4 - 32122206 (07.30.2019) apk. installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the resize button from the left side of the URL bar.
2. Select the "3x" option and click the "check" button.
3. Open a second window by clicking the "+" sign from the tray.
4. Open a 3rd window by clicking the "+" sign again.

**[Expected results]:**
**Step3:**  A second window is opened and all windows are correctly displayed.
**Step4:**  A 3rd window is opened and all windows are correctly displayed.

**[Actual results]:**
**Step3:**  A second window is opened but the UI for the first one breaks.
**Step4:**  The app crashes.

**[Notes]:**
- This issue is also reproducible with sizes that are close to the "3x" size (manual resize).
- I was not able to reproduce this issue on HTC Vive Focus Plus.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1yaKouZncyc3SPe28kO1qM0_bafkAA5Dw)

**Comment by keianhzo** [comment] 2019-08-21 18:10
@Softvision-GeluHaiduc Cannot reproduce this issue before or after #1624 Can you please try again after #1624 is merged or provide more specific STRs maybe there is some detail that we are missing or some initial state?

**Comment by Softvision-GeluHaiduc** [comment] 2019-08-22 09:10
@keianhzo I have verified that this issue is still reproducible with the latest Firefox Reality-1.4-32332324(08.22.2019) installed on the Oculus Go and Oculus Quest  headsets.
However, I saw some different behaviours between the devices:

**[Oculus Go]:**
- On this headset “Step3: A second window is opened but the UI for the first one breaks.” is not reproducible but the crash is still happening after the third window is opened.
- The issue was not reproducible if the new window creation was not rushed.
-  Attached a screen recording of the issue [here](https://drive.google.com/file/d/1r4qcyl-SumqJeetPWyOGZD79K20UrAqC/view?usp=sharing) and I also attached the logcat file [here](https://drive.google.com/file/d/1ySaAbJQ_ltO63N9c2jASgmkE-gfvE01Y/view?usp=sharing).

**[Oculus Quest]:**
- On this headset the issue is completely reproducible, “Step3: A second window is opened but the UI for the first one breaks.” this step is reproducible only 80% of the time but the crash always happens.
-  Attached a screen recording of the issue [here](https://drive.google.com/file/d/11-O7sQoqY_8R9vN0UVuTz3bxG1lRad8C/view?usp=sharing).

**Comment by MortimerGoro** [comment] 2019-08-27 07:14
I think this is also fixed by #1639. @Softvision-GeluHaiduc Please test again with the current master

**Closed by MortimerGoro** 2019-08-27 07:14 UTC
Labels: P2, [QA]:Blocker issue

**Comment by Softvision-GeluHaiduc** [comment] 2019-08-27 08:40
I have verified that this issue is no longer reproducible with the latest Firefox Reality 1.4-32390648 installed on the Oculus Go headset. 
Now, the app does not crashes after opening a 3rd window if the first one has a "3x" size.
