### ISSUE TITLE
3x window size feels uncomfortably close

### ISSUE THREAD

**Issue by caseyyee** [MozillaReality/FirefoxReality#884] opened 2018-12-07 15:17 UTC
## Hardware
Go
FXR 1.1

## Steps to Reproduce
1. Enter window resize mode
2. Click 3x

## Current Behavior
Window becomes 3X size, but feels uncomfortable to view due to how close it is.

## Expected Behavior
Window should move back in space for more comfortable viewing. This probably means a bigger window, maybe UI that scales?

**Comment by philip-lamb** [comment] 2019-05-03 10:07
Duplicate of #480.

**Closed by philip-lamb** 2019-05-03 10:07 UTC
Labels: UX
