### ISSUE TITLE
[Pico][!NSFW]VR Video plays incorrectly in mobile mode and desktop mode

### ISSUE THREAD

**Issue by picoxr** [MozillaReality/FirefoxReality#3192] opened 2020-04-20 12:29 UTC
## Configuration

Firefox Reality version: Firefox Reality version 10-141060720
Firefox Reality build ID: 9b36c14

Hardware: 
Pico G2 4K - Android - 8.1.0

## Steps to Reproduce

1. Open video website [NSFW here](https://www.pornhub.com/view_video.php?viewkey=ph5dc7f2e972834).
2. Click play button
3.

## Current Behavior

VR videos play with sound only but no images in non-desktop mode. While in desktop mode, videos can play but rotates violently and doesn't follow head movement correctly.

## Expected Behavior

VR videos play correctly in panoramic view in mobile mode.

## Context

Hope to support viewing VR video from Pornhub.com

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by fernandojsg** [comment] 2020-05-01 12:14
This seems related to https://github.com/MozillaReality/FirefoxReality/issues/3191 (and https://bugzilla.mozilla.org/show_bug.cgi?id=1619550) as both are using HLS for streaming video using m3u8 and have similar results, a black frame but with sound.

**Comment by miketaylr** [comment] 2020-05-01 19:03
We have some related reports of VR (NSFW) content being audio-only:

https://github.com/webcompat/web-bugs/issues/51497
https://github.com/webcompat/web-bugs/issues/50356
https://github.com/webcompat/web-bugs/issues/50460
(this one says "it worked ok until mid-february")
https://github.com/webcompat/web-bugs/issues/50223
"idk it just started happening"

Given the pattern of breaking on multiple different sites, I'm inclined to think this is a core issue, not a webcompat one.

**Comment by bluemarvin** [comment] 2020-05-01 19:05
If they are DelightVR based then it isn't surprising: https://github.com/MozillaReality/FirefoxReality/issues/3301

It looks like they rolled out an update that broke FxR.

**Comment by bluemarvin** [comment] 2020-05-01 19:10
@miketaylr The DellightVR player could be a webcompat issue? I know cvan previous worked with them to fix their player and be compatible with FxR/GeckoView.

**Comment by miketaylr** [comment] 2020-05-01 19:11
Could be -- I need to check each of these sites to see if they're using DelightVR.

**Comment by fernandojsg** [comment] 2020-05-01 19:30
fwiw I checked the network request and czechvr.com and vrporn.com both uses DelightVR 2.0.16.
xhamster seems to use a custom solution based on three.js and pornhub seems to be using also a custom raw webgl solution.

**Comment by miketaylr** [comment] 2020-05-01 19:42
Thanks for checking @fernandojsg. It sounds like there are a few playback bugs with HLS, and WebGL (three.js + pornhub) to investigate.

**Comment by bluemarvin** [comment] 2020-05-22 00:25
I did a little more investigating into this issue and have found several issues. The page fails to enter VR mode due to missing a user interaction. There is one, but we miss it. If the user interaction requirement it turned off, VR may be entered but the code seems to have issue reading the heading so the video is locked. Probably related to this issue:
```
Uncaught TypeError: can't access property "getViewerPose", this._frameData is undefined
    value dl8-98c2453503bb35523e4559d44392cad68bbebf42.js:45849
    value dl8-98c2453503bb35523e4559d44392cad68bbebf42.js:1382
```

**Comment by bluemarvin** [comment] 2020-05-22 00:27
Since this site uses delight-vr player, it is a dupe of https://github.com/MozillaReality/FirefoxReality/issues/3301

**Closed by bluemarvin** 2020-05-22 00:27 UTC
Labels: blocked-media
