### ISSUE TITLE
[Oculus] The app crashes after resuming the app from immersive mode if the "Enable UI Hardware Acceleration" option is enabled

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2412] opened 2019-12-03 16:01 UTC
**[Affected Versions]:**
- Firefox Reality version 7 RC5 (0706b656)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The "Enable UI Hardware Acceleration" option from "Developer Options" card is enabled.

**[Steps to reproduce]:**
1. Open and Play a 360 video in immersive mode.
2. Click the "Oculus" button from the controller.
3. Click on one of the buttons displayed in the prompt.

**[Expected results]:**
- The app is quited or resumed depending on the clicked button.

**[Actual results]:**
- **"Quit"** button - The app is quited and after it's reopen the crash dialog box is displayed.
- **"Resume"** button - The app is closed instead of resumed and after it's reopen the crash dialog box is displayed.
- **"Take Photo"** button - The app is closed instead of resumed and after it's reopen the crash dialog box is displayed.

**[Additional Notes]:**
- The Youtube page appears to be broken after resuming the app and dismissing the crash dialog box. 
- I was not able to reproduce this issue on the HTC devices.
- Attached are a screen recording along with the logcat and the crash report of the issue: 
	- Screen recording: [link](https://drive.google.com/open?id=1jnfvrbPiQUSRDtTiJNHSaRn1hT8J9HsG).
	- Logcat: [link](https://drive.google.com/open?id=12rqqqod_JbbuwYu5YNmEfDOM1I5JJZcb).
	- Crash report: [link](https://crash-stats.mozilla.com/report/index/bp-6196dc4c-5630-4073-b21e-4cbef0191203).

**Comment by bluemarvin** [comment] 2019-12-03 16:08
This is the whole reason we turned software rendering on and is why hardware rendering is no longer the default. This is just a dupe of the previous crash on exit. I don’t see how this is a blocking issue.

**Comment by MortimerGoro** [comment] 2019-12-03 16:16
Duplicate of #1959

**Closed by MortimerGoro** 2019-12-03 16:16 UTC
Labels: [QA]:Blocker issue, duplicate
