### ISSUE TITLE
Bookmarks menu broken on WaveVR

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#951] opened 2019-02-14 23:58 UTC
## Hardware

Vive Focus FxR 1.1.2
## Steps to Reproduce

1. Do a clean install of FxR
2. Do a voice search
3. Make a bookmark by pressing the star in the url bar.
4. Click the bookmark menu button in the try.

## Current Behavior

The main window disappears.
## Expected Behavior

The bookmarks should be displayed in the bookmark window.

## Comments
This appears to be a first run bug. If I do a clean install this reproduces every time. But if I kill and relaunch then book marks work as expected.

**Comment by MortimerGoro** [comment] 2019-02-15 11:49
I can't reproduce this one either. I'm removing the app via `adb uninstall org.mozilla.vrbrowser` and launching it using Android Studio. Are your reproducing it the same way?

**Comment by bluemarvin** [comment] 2019-02-15 17:36
Fresh install, no bookmark window is rendered:
![screen_shot_1902153236](https://user-images.githubusercontent.com/3066/52873837-d08c5a00-3104-11e9-85af-32e59a5cb33b.png)

After restarting:
![screen_shot_1902153519](https://user-images.githubusercontent.com/3066/52873939-10534180-3105-11e9-8e8f-72f0bb7d2d4b.png)

**Comment by philip-lamb** [comment] 2019-02-20 00:58
I was able to reproduce this. On first run (Vive Focus OS v1.92.1400.2) the bookmarks and the settings windows weren't showing. It appeared that the surface was there but transparent, as the pointer dot could be placed on the surface.

After a relaunch (`adb shell am force-stop org.mozilla.vrbrowser`) both bookmarks and settings window work as expected.

**Comment by MortimerGoro** [comment] 2019-03-14 18:56
Fixed via https://github.com/MozillaReality/FirefoxReality/pull/1012

**Closed by MortimerGoro** 2019-03-14 18:56 UTC
Labels: bug, platform:WaveVR
