### ISSUE TITLE
[FxA] The deleted synced history feeds are brought back after two ore more are deleted using the delete trash button 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [MozillaReality/FirefoxReality#2653] opened 2020-01-15 16:56 UTC
**[Notes]:**
- This issue is reproducible even after logging out from the FxA account.
- However, this issue is not reproducible while History is not synced. 

**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- You are logged into an FxA account and the History is synced.

**[Steps to reproduce]:**
1. Click the History button from the tray.
2. Delete two ore more feeds using the delete trash button.
3. Observe the behavior.

**[Expected results]:**
- The feeds are successfully deleted.

**[Actual results]:**
- The feeds are brought back.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1s5iLJz4QeIA03f5STVSHjNxB89kqt6mg).

**Comment by keianhzo** [comment] 2020-01-17 11:20
@Softvision-RemusDranca Isn't this a duplicate of https://github.com/MozillaReality/FirefoxReality/issues/2408? 

https://github.com/MozillaReality/FirefoxReality/pull/2658 should fix both

**Comment by Softvision-RemusDranca** [comment] 2020-01-17 11:57
@keianhzo, I think that you are right. After looking closely to the feeds titles in both videos. 
In the first one I misinterpreted that it's only a UI issue but the deleted feeds are brought back and the scrolling of the page is just a side effect. Sorry if I may have misled you in  #2408.

**Comment by keianhzo** [comment] 2020-01-20 10:34
No worries @Softvision-RemusDranca the PR should close both. Just wanted to make sure I wasn't missing anything.

**Closed** 2020-01-21 17:41 UTC
Labels: [QA]:Major issue, in progress, regression

**Comment by heres-maria** [comment] 2020-01-22 10:43
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 8 RC4 (f9c92a23) build. 
However, a new behavior was observed: some feeds can no longer be deleted after a sync. This is documented in issue #2697. 
Tested on Oculus Go (Android 7.1.2), Oculus Quest (Android 7.1.1), HTC Vive Focus Plus (Android 7.1.2) and HTC Vive Focus (Android 7.1.2).
