### ISSUE TITLE
[Pico] The Bookmark/History Views are not restored after reopening the app

### ISSUE THREAD

**Issue by Softvision-GeluHaiduc** [MozillaReality/FirefoxReality#2861] opened 2020-02-25 15:12 UTC
**[Affected Versions]:**
- Firefox Reality version 9 RC3 (18aba8be)

**[Affected Platforms]:**
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure the Bookmark/History View is displayed.

**[Steps to reproduce]:**
1. Press the Pico button on the controller.
2. Double press the Pico button on the controller and close all the open apps.
3. Reopen the app and observe the behaviour.

**[Expected results]:**
- The Bookmark/History Views are restored.

**[Actual results]:**
- The Bookmark/History Views are not restored.

**[Notes]:**
- The webpages are still restored.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1WLwKruJ1f3TDWuNk2T035fUQRlECLjlZ).

**Comment by keianhzo** [comment] 2020-02-25 15:37
@Softvision-GeluHaiduc I Can't reproduce this issue. There must be something else going on. Can't you share a logcat? Does it also happen even if you don't get the boundaries configuration app when going out of the app?

**Comment by Softvision-GeluHaiduc** [comment] 2020-02-26 12:07
@keianhzo I tried it multiple times sometimes with boundary and without and it seems to be intermittent [here](https://drive.google.com/open?id=1ZogEZYpdHLjU0qz8mN7843l_iffv0smj) is the logcat of 2 attempts once with the boundary, and the issue dis not reproduce, and once without the boundary and the issue reproduced.

**Comment by bluemarvin** [comment] 2020-04-14 21:40
I think I reproduced this once. I had downloads, bookmarks, and history open when I quit and resumed and one of the windows restored with the feed instead of the history window. One of the windows got stuck in bookmark view for me and I had to close it. I'll see if I can find a pattern.

**Comment by bluemarvin** [comment] 2020-04-15 22:14
The window getting stuck was a different issue.

**Closed** 2020-04-20 18:52 UTC
Labels: [QA]:Normal issue, in progress

**Comment by Softvision-GeluHaiduc** [comment] 2020-04-21 14:35
I have verified that this issue is no longer reproducible with the latest Firefox Reality version 10-141111916 (d9a7eec5) installed on the Pico Neo2 and Pico G2 4K headsets.
Now, the Bookmark/History/Downloads Views are restored after reopening the app.
